// dec_patterngen.v — in-fabric SERIAL PATTERN GENERATOR with FAULT INJECTION.
//
// PURPOSE
//   Drive the decode front-end INPUTS (the pre-sliced code lines the UART/I2C/
//   SPI decoders consume) with configurable, deterministic patterns that include
//   CLEAN data bytes AND real protocol FAULTS, so the extended decode trigger
//   modes 1(error)/2(sequence)/3(addr) can be PROVEN on real silicon over GPMC
//   with NO bench signal source connected. This is a strict superset of the
//   clean-only loopback test-gens already embedded in each decoder: those emit
//   correct frames only; this one additionally injects framing/parity/NAK faults,
//   an addressed transaction with R/W, contiguous multi-byte sequences and a
//   deliberate near-miss.
//
// HOW IT REACHES THE DECODERS (integration, additive)
//   acq.v muxes these outputs AHEAD of the decoder slicers: when the master
//   enable is asserted, dec_sample_code / dec_a / dec_b are sourced from here
//   instead of the live cap_word channel, and each decoder's OWN internal
//   test-gen is held off (its .tg_en tied 0). Gen-OFF (master enable 0) restores
//   today's wiring byte-for-byte, so the invariant "gen-off == today" holds and
//   the IFACE_BUILD_ID is unaffected (no schema / selector change; the mux is a
//   pure combinational addition on previously-existing wires).
//
// ARMING (over GPMC, NO new selector — see plan/patterngen.md for the exact map)
//   MASTER ENABLE : the EXISTING tg_en = dec_cfg[9] (CFG 0x04 bit 9). 1 => this
//                   generator drives the front-end; 0 => inert / today.
//   SCRIPT SELECT : the EXISTING dec_proto = dec_cfg[11:10] picks which protocol
//                   script plays (0=UART, 1=I2C, 2=SPI; 3=ETH reserved, see note).
//   BIT TIMING    : UART bit width = integer part of the EXISTING dec_spb
//                   (SEL_DEC_SPB 0x0c/0x1c, Q16.8); load the SAME spb the UART
//                   decoder uses so generator and sampler agree. I2C/SPI use a
//                   fixed internal half-period (edge-timed decoders need no spb).
//   No bit outside {tg_en, dec_proto, dec_spb, dec_thr} is consumed, and NONE of
//   those are new — every one already exists and is documented in the DEC map.
//   The generated byte VALUES are fixed constants (below); the host aligns the
//   trigger MATCH/TESTGEN/err-mask to those documented constants — see the plan.
//
// WHY FIXED-CONSTANT SCRIPTS (not config-driven bytes)
//   A looping script with DISTINCT, documented byte values lets one arming prove
//   BOTH a positive (the matching mode fires: matched=1 + correct matched_byte)
//   and a negative (a clean byte / a non-adjacent near-miss does NOT fire) purely
//   by choosing the trigger config — no per-scenario selector bit is needed,
//   which is strictly cleaner than stealing one.
//
// FORMAT ASSUMPTIONS (documented so the host configures the decoder to match)
//   UART : 8 data bits, LSB-first, EVEN parity, 1 stop bit. Host must set
//          dec_bits=0(=>8), dec_par=1(even). The generator computes even parity
//          for every clean frame and INVERTS it for the parity-fault frame; it
//          drives the stop bit LOW for the framing-fault frame. The decoder
//          derives frame_err/parity_err itself from the waveform (real fault).
//   I2C  : MSB-first, 8-bit units, one ACK/NAK clock per unit. START then an
//          ADDRESS unit {addr7,rw} then DATA units; the generator drives SDA high
//          on the 9th (ACK) clock of the fault unit to make a real NAK.
//   SPI  : mode 0 (CPOL=0,CPHA=0), MSB-first, 8-bit words, sampled on CLK rising.
//          Host must set dec_cfg cpol=0,cpha=0,msb=1.
//
// ETH (proto==3): reserved / not driven here. 100BASE-TX injection needs a full
//   in-fabric 4b5b+scramble+MLT-3 line encoder feeding eth_wr_samp at 200 MHz —
//   a separate module. Modes 1/2/3 are ALREADY retired in silicon by the UART/
//   I2C scripts above (frame_err/parity_err/NAK for mode 1, the contiguous
//   sequence for mode 2, the I2C address for mode 3), so ETH is a documented
//   extension point, not a blocker. proto==3 leaves all lines idle.
//
// TIMING MODEL: all state advances ONLY on cap_tick, so "column" == cap_tick,
// exactly like the decoders it feeds. Outputs are pure rails (0x00 / 0xFF) so
// any decoder threshold in [1..255] slices them correctly.

`default_nettype none

module dec_patterngen (
    input  wire        clk,        // 80 MHz single domain
    input  wire        cap_tick,   // one pulse per decimated column
    input  wire        en,         // MASTER ENABLE = tg_en (dec_cfg[9]); 0 => inert
    input  wire [1:0]  proto,      // dec_proto (dec_cfg[11:10]): 0=UART 1=I2C 2=SPI 3=ETH
    input  wire [23:0] spb,        // dec_spb (Q16.8); UART bit width = spb[15:8]

    // pre-sliced code outputs (rails 0x00 / 0xFF) muxed ahead of the slicers:
    output reg  [7:0]  gen_uart_code, // -> dec_sample_code (UART)
    output reg  [7:0]  gen_a_code,    // -> dec_a (I2C SCL / SPI CLK)
    output reg  [7:0]  gen_b_code     // -> dec_b (I2C SDA / SPI DATA)
);

    // protocol codes
    localparam [1:0] P_UART = 2'd0, P_I2C = 2'd1, P_SPI = 2'd2, P_ETH = 2'd3;

    // fixed half-periods (columns) for the edge-timed protocols
    localparam integer I2C_HOLD = 4;   // cap_ticks per I2C SCL half-segment
    localparam integer SPI_HOLD = 8;   // cap_ticks per SPI CLK half-segment

    // script gaps (UART, in BIT units)
    localparam integer UART_SMALL = 2;    // contiguous inter-frame idle (adjacent)
    localparam integer UART_BIG   = 64;   // idle that breaks mode-2 adjacency

    // ---- documented fixed byte constants (host aligns triggers to these) ----
    // UART frames: {byte, badstop, badparity, gap_after_bits}
    //   0xC1 clean | 0x5A framing-fault | 0x3C parity-fault |
    //   0xAA,0xBB contiguous SEQUENCE | 0x33,0x44 NON-adjacent near-miss
    // I2C  : addr 0x48 (=addr 0x24, W) | data 0xD5 NAK | data 0xAA,0xBB ACK seq
    // SPI  : words 0xAA, 0xBB, 0xC3
    // (constants are materialised directly in the ROM-fill loops below.)

    // ==================================================================
    // ROM storage (constant => inferred as logic ROM, ramstyle=logic keeps
    // it out of the full M9K pool, same policy as the decoders' test-gens).
    // ==================================================================
    localparam integer UART_CAP = 512;
    localparam integer I2C_CAP  = 256;
    localparam integer SPI_CAP  = 256;

    // Loop lengths are CONSTANTS in the datapath (synthesis-safe: not read from an
    // initial-set reg). The initial fills below also compute the filled count into
    // uart_len/i2c_len/spi_len and a sim assertion checks they equal these — so a
    // future script edit that forgets to update the constant fails LOUD in sim.
    localparam integer UART_LEN = 343;   // 4 lead + 7*(1+8+1+1) + gaps(2+2+64+2+64+64+64)
    localparam integer I2C_LEN  = 81;    // 2 lead + START(2) + 4*(16+2) + STOP(3) + 2 idle
    localparam integer SPI_LEN  = 68;    // 2 lead + 3*(16 + 6 gap)

    (* ramstyle = "logic" *) reg uart_rom [0:UART_CAP-1]; // 1 = line high
    (* ramstyle = "logic" *) reg i2c_scl  [0:I2C_CAP-1];
    (* ramstyle = "logic" *) reg i2c_sda  [0:I2C_CAP-1];
    (* ramstyle = "logic" *) reg spi_clk  [0:SPI_CAP-1];
    (* ramstyle = "logic" *) reg spi_data [0:SPI_CAP-1];

    reg [15:0] uart_len;   // sim-only: filled entry count (asserted == UART_LEN)
    reg [15:0] i2c_len;
    reg [15:0] spi_len;

    // ---------------- UART script fill ----------------
    integer u_i, uf, ubit, ug;
    reg [7:0]  u_byte;
    reg        u_bad_stop, u_bad_par, u_pbit;
    integer    u_gap;
    // frame table
    reg [7:0]  uf_byte  [0:6];
    reg        uf_bstop [0:6];
    reg        uf_bpar  [0:6];
    integer    uf_gap   [0:6];
    integer    uk;

    initial begin
        for (u_i = 0; u_i < UART_CAP; u_i = u_i + 1) uart_rom[u_i] = 1'b1; // idle high
        // frame table (byte, badstop, badpar, gap_after_bits)
        uf_byte[0]=8'hC1; uf_bstop[0]=0; uf_bpar[0]=0; uf_gap[0]=UART_SMALL; // clean
        uf_byte[1]=8'h5A; uf_bstop[1]=1; uf_bpar[1]=0; uf_gap[1]=UART_SMALL; // framing fault
        uf_byte[2]=8'h3C; uf_bstop[2]=0; uf_bpar[2]=1; uf_gap[2]=UART_BIG;   // parity fault
        uf_byte[3]=8'hAA; uf_bstop[3]=0; uf_bpar[3]=0; uf_gap[3]=UART_SMALL; // seq #1
        uf_byte[4]=8'hBB; uf_bstop[4]=0; uf_bpar[4]=0; uf_gap[4]=UART_BIG;   // seq #2 (adj to #1)
        uf_byte[5]=8'h33; uf_bstop[5]=0; uf_bpar[5]=0; uf_gap[5]=UART_BIG;   // near-miss #1
        uf_byte[6]=8'h44; uf_bstop[6]=0; uf_bpar[6]=0; uf_gap[6]=UART_BIG;   // near-miss #2 (NOT adj)

        u_i = 0;
        // lead idle so the sampler sees a stable high before the first start edge
        for (uk = 0; uk < 4; uk = uk + 1) begin uart_rom[u_i]=1'b1; u_i=u_i+1; end
        for (uf = 0; uf < 7; uf = uf + 1) begin
            u_byte     = uf_byte[uf];
            u_bad_stop = uf_bstop[uf];
            u_bad_par  = uf_bpar[uf];
            u_gap      = uf_gap[uf];
            u_pbit     = (^u_byte) ^ u_bad_par;      // even parity, inverted on fault
            // START bit (low)
            uart_rom[u_i]=1'b0; u_i=u_i+1;
            // 8 data bits, LSB-first
            for (ubit = 0; ubit < 8; ubit = ubit + 1) begin
                uart_rom[u_i] = u_byte[ubit]; u_i=u_i+1;
            end
            // parity bit (even)
            uart_rom[u_i] = u_pbit; u_i=u_i+1;
            // stop bit (high, or low on framing fault)
            uart_rom[u_i] = u_bad_stop ? 1'b0 : 1'b1; u_i=u_i+1;
            // inter-frame idle (high)
            for (ug = 0; ug < u_gap; ug = ug + 1) begin uart_rom[u_i]=1'b1; u_i=u_i+1; end
        end
        uart_len = u_i[15:0];
    end

    // ---------------- I2C script fill ----------------
    integer c_i, ci_b, ci_k;
    reg [7:0]  ci_bytes [0:3];
    reg        ci_ack   [0:3];     // 1 = NAK on 9th clock
    reg [7:0]  ci_byte;
    reg        ci_a;
    initial begin
        for (c_i = 0; c_i < I2C_CAP; c_i = c_i + 1) begin
            i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b1;  // idle high
        end
        ci_bytes[0]=8'h48; ci_ack[0]=1'b0; // ADDRESS (0x24 W) + ACK
        ci_bytes[1]=8'hD5; ci_ack[1]=1'b1; // DATA + NAK  (mode-1 error)
        ci_bytes[2]=8'hAA; ci_ack[2]=1'b0; // DATA + ACK  (seq #1)
        ci_bytes[3]=8'hBB; ci_ack[3]=1'b0; // DATA + ACK  (seq #2, adjacent)

        c_i = 0;
        // lead idle (SCL=1,SDA=1) primes prev_sda=1 for the START
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b1; c_i=c_i+1;
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b1; c_i=c_i+1;
        // START: SDA 1->0 while SCL high, then SCL low
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b0; c_i=c_i+1;
        i2c_scl[c_i]=1'b0; i2c_sda[c_i]=1'b0; c_i=c_i+1;
        // 4 units, MSB-first, each + one ACK/NAK clock
        for (ci_b = 0; ci_b < 4; ci_b = ci_b + 1) begin
            ci_byte = ci_bytes[ci_b];
            ci_a    = ci_ack[ci_b];
            for (ci_k = 7; ci_k >= 0; ci_k = ci_k - 1) begin
                i2c_scl[c_i]=1'b0; i2c_sda[c_i]=ci_byte[ci_k]; c_i=c_i+1; // setup
                i2c_scl[c_i]=1'b1; i2c_sda[c_i]=ci_byte[ci_k]; c_i=c_i+1; // clock/sample
            end
            i2c_scl[c_i]=1'b0; i2c_sda[c_i]=ci_a; c_i=c_i+1; // ACK/NAK setup
            i2c_scl[c_i]=1'b1; i2c_sda[c_i]=ci_a; c_i=c_i+1; // ACK/NAK clock
        end
        // STOP: SCL low, SCL high w/ SDA low, then SDA 0->1
        i2c_scl[c_i]=1'b0; i2c_sda[c_i]=1'b0; c_i=c_i+1;
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b0; c_i=c_i+1;
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b1; c_i=c_i+1;
        // trailing idle (inter-transaction gap)
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b1; c_i=c_i+1;
        i2c_scl[c_i]=1'b1; i2c_sda[c_i]=1'b1; c_i=c_i+1;
        i2c_len = c_i[15:0];
    end

    // ---------------- SPI script fill (mode 0, MSB-first) ----------------
    integer s_i, si_w, si_k, si_g;
    reg [7:0]  si_words [0:2];
    reg [7:0]  si_word;
    localparam integer SPI_GAP = 6;   // idle (CLK low) segments between words
    initial begin
        for (s_i = 0; s_i < SPI_CAP; s_i = s_i + 1) begin
            spi_clk[s_i]=1'b0; spi_data[s_i]=1'b0;  // CLK idle low (CPOL=0)
        end
        si_words[0]=8'hAA; si_words[1]=8'hBB; si_words[2]=8'hC3;
        s_i = 0;
        // lead idle (CLK low) — primes prev_clk=0, no edge
        spi_clk[s_i]=1'b0; spi_data[s_i]=1'b0; s_i=s_i+1;
        spi_clk[s_i]=1'b0; spi_data[s_i]=1'b0; s_i=s_i+1;
        for (si_w = 0; si_w < 3; si_w = si_w + 1) begin
            si_word = si_words[si_w];
            for (si_k = 7; si_k >= 0; si_k = si_k - 1) begin
                spi_clk[s_i]=1'b0; spi_data[s_i]=si_word[si_k]; s_i=s_i+1; // setup (CLK low)
                spi_clk[s_i]=1'b1; spi_data[s_i]=si_word[si_k]; s_i=s_i+1; // rising -> sample
            end
            // inter-word idle gap (CLK low, no edges)
            for (si_g = 0; si_g < SPI_GAP; si_g = si_g + 1) begin
                spi_clk[s_i]=1'b0; spi_data[s_i]=1'b0; s_i=s_i+1;
            end
        end
        spi_len = s_i[15:0];
    end

    // ==================================================================
    // sequencer: hold each ROM entry for the proto's column-width, loop.
    // ==================================================================
    wire [15:0] uart_hold_w = (spb[15:8] == 8'd0) ? 16'd1 : {8'd0, spb[15:8]};
    reg  [15:0] cur_n;
    reg  [15:0] cur_hold;
    always @* begin
        case (proto)
            P_UART: begin cur_n = UART_LEN[15:0]; cur_hold = uart_hold_w;    end
            P_I2C:  begin cur_n = I2C_LEN[15:0];  cur_hold = I2C_HOLD[15:0]; end
            P_SPI:  begin cur_n = SPI_LEN[15:0];  cur_hold = SPI_HOLD[15:0]; end
            default:begin cur_n = 16'd1;          cur_hold = 16'd1;          end // ETH: idle
        endcase
    end

    // synthesis-neutral sim guard: the initial-computed fill counts must match the
    // datapath constants above (catches a script edit that desyncs the two).
    // synthesis translate_off
    initial begin
        #1;
        if (uart_len !== UART_LEN || i2c_len !== I2C_LEN || spi_len !== SPI_LEN) begin
            $display("dec_patterngen LEN MISMATCH: uart=%0d/%0d i2c=%0d/%0d spi=%0d/%0d",
                     uart_len, UART_LEN, i2c_len, I2C_LEN, spi_len, SPI_LEN);
            $finish;
        end
    end
    // synthesis translate_on

    reg [15:0] seg;
    reg [15:0] hold;
    always @(posedge clk) begin
        if (!en) begin
            seg  <= 16'd0;
            hold <= 16'd0;
        end else if (cap_tick) begin
            if ((hold + 16'd1) >= cur_hold) begin
                hold <= 16'd0;
                seg  <= ((seg + 16'd1) >= cur_n) ? 16'd0 : (seg + 16'd1);
            end else begin
                hold <= hold + 16'd1;
            end
        end
    end

    // ==================================================================
    // output drive (rails). Inactive lines idle; the losing decoders are
    // gated inert by the parent so their inputs are don't-care. ROM reads are
    // continuous-assign taps (same style as the decoders' test-gens) so the
    // combinational mux is sensitive only to the tapped bits, not whole arrays.
    // ==================================================================
    wire uart_bit = uart_rom[seg];
    wire scl_bit  = i2c_scl[seg];    // only meaningful when proto==I2C
    wire sda_bit  = i2c_sda[seg];
    wire sck_bit  = spi_clk[seg];    // only meaningful when proto==SPI
    wire mosi_bit = spi_data[seg];

    always @* begin
        // defaults: UART idle high, I2C bus idle high, SPI clk/data idle low
        gen_uart_code = 8'hFF;
        gen_a_code    = 8'hFF;
        gen_b_code    = 8'hFF;
        case (proto)
            P_UART: begin
                gen_uart_code = uart_bit ? 8'hFF : 8'h00;
            end
            P_I2C: begin
                gen_a_code = scl_bit ? 8'hFF : 8'h00;   // SCL
                gen_b_code = sda_bit ? 8'hFF : 8'h00;   // SDA
            end
            P_SPI: begin
                gen_a_code = sck_bit  ? 8'hFF : 8'h00;  // CLK
                gen_b_code = mosi_bit ? 8'hFF : 8'h00;  // DATA
            end
            default: begin
                gen_a_code = 8'h00;   // ETH reserved: idle
                gen_b_code = 8'h00;
            end
        endcase
    end

endmodule

`default_nettype wire
