// eth_descramble.v — 100BASE-TX self-synchronising descrambler.
//
// GOLDEN-MODEL ORACLE: app/internal/eth100tx/decode.go  func descramble().
// This RTL reproduces that function BIT-FOR-BIT on the emitted vectors
// (vectors/<case>.scrambled_bits -> vectors/<case>.plain_bits).
//
// 100BASE-TX uses a SIDE-STREAM (additive) scrambler, NOT a multiplicative
// self-synchronising one: the keystream is generated by an 11-bit LFSR with
// feedback polynomial x^11 + x^9 + 1 and is XORed onto the data, INDEPENDENT of
// the data. So the descrambler must REGENERATE the identical keystream and XOR
// it back on. The load-bearing trick is recovering the transmitter's 11-bit
// LFSR phase from the wire (IDLE-LOCK), because the keystream is data-blind.
//
//   Keystream recurrence (verified against vectors/*.keystream):
//       key[n] = key[n-9] ^ key[n-11]
//   Additive descramble:  plain[n] = scrambled[n] ^ key[n]
//
// PLACEMENT IN THE CHAIN (pinned to the golden model): descramble is applied to
// the RAW RECOVERED BIT STREAM (MLT-3-decode output = the scrambled 125 Mbit
// NRZ bits) BEFORE 4B5B alignment/decode. TX order is
//   MII -> 4B5B -> serialize MSB-first -> SCRAMBLE -> MLT-3;
// RX reverses, so descramble sits directly after mlt3Decode and before
// align5B — exactly where DecodeSamples() calls it.
//
// IDLE-LOCK (the golden model's descramble(), need=11, verify=33):
//   During inter-frame IDLE the 4B5B code is /I/ = 11111 (all-ones plaintext),
//   so scrambled[n] = key[n] ^ 1, i.e. the received idle bits EXPOSE ~key.
//     * HUNT   : load 11 consecutive (in_bit ^ 1) into the LFSR state (seed).
//     * VERIFY : free-run the LFSR; require the next 33 descrambled bits to be
//                all-ones (still idle). Any failure -> re-hunt (re-seed from the
//                following bit). This rejects a bad phase guess.
//     * LOCKED : LFSR free-runs; `locked` asserts; plain = in ^ key streams out.
//   On the clean leading idle both vectors lock at bit offset 0 (LockOffset==0
//   in the model), so `locked` asserts after the 11+33 = 44 lead-in bits, far
//   inside the >=160-bit leading IDLE — and because the plaintext is idle (all
//   ones) throughout HUNT/VERIFY, the descrambled output is already bit-exact
//   from the very first bit.
//
// STREAMING INTERFACE: one bit per asserted in_valid. Output is registered
// (1 in_valid -> next-cycle out_valid), latency = 1 valid beat. The spec's
// 2-bits/clk CDR feed is served by unrolling the LFSR by 2 (compute key[n],
// key[n+1] combinationally, advance state by 2) — kept 1-lane here for a clean
// bit-exact standalone proof; the recurrence and FSM are identical per lane.
//
// RESOURCES: 11 FF LFSR + a 6-bit seed/verify counter + 2-bit FSM + a handful
// of XORs. 0 M9K, 0 PLL, 0 pins. Additive/gated: with en=0 (or rst) the module
// is fully inert (locked=0, out_valid=0) — the fabric-inertness contract.

module eth_descramble #(
    parameter integer SEED_LEN   = 11,  // idle bits to seed the LFSR (need)
    parameter integer VERIFY_LEN = 33   // idle bits that must descramble to 1
) (
    input  wire clk,
    input  wire rst,        // synchronous, active-high: full reset to HUNT
    input  wire en,         // engine gate; en=0 holds the module inert

    // ---- scrambled bit stream in (MLT-3-decode output) ----
    input  wire in_valid,   // 1 = in_bit is a valid scrambled bit this clk
    input  wire in_bit,     // scrambled NRZ bit

    // ---- descrambled bit stream out ----
    output reg  out_valid,  // 1 = out_bit valid (registered, 1-beat latency)
    output reg  out_bit,    // descrambled (plain) NRZ bit
    output reg  locked      // 1 once idle-lock is verified; sticky until rst/!en
);

    // FSM states.
    localparam [1:0] S_HUNT   = 2'd0,   // collecting SEED_LEN seed bits
                     S_VERIFY = 2'd1,   // checking VERIFY_LEN idle bits
                     S_LOCKED = 2'd2;   // synchronised, streaming
    reg [1:0] state;

    // 11-bit LFSR. Convention: lfsr[0] = key[n-1] (most recent), lfsr[10] =
    // key[n-11]. Next keystream bit = key[n] = key[n-9] ^ key[n-11] =
    // lfsr[8] ^ lfsr[10]. Advance = shift left, new key bit into lfsr[0].
    reg [10:0] lfsr;

    // Seed/verify progress counter (wide enough for max(SEED_LEN,VERIFY_LEN)).
    reg [5:0] cnt;

    // Combinational per-bit temporaries.
    reg key_bit;   // regenerated keystream bit for this input bit
    reg seed_bit;  // idle-derived seed bit = in_bit ^ 1
    reg plain_bit; // descrambled bit = in_bit ^ key_bit

    always @(posedge clk) begin
        if (rst || !en) begin
            state     <= S_HUNT;
            lfsr      <= 11'd0;
            cnt       <= 6'd0;
            out_valid <= 1'b0;
            out_bit   <= 1'b0;
            locked    <= 1'b0;
        end else begin
            // out_valid tracks in_valid with one cycle of pipeline latency.
            out_valid <= in_valid;

            if (in_valid) begin
                case (state)
                    // ---- HUNT: seed the LFSR from idle-exposed key bits ----
                    S_HUNT: begin
                        seed_bit  = in_bit ^ 1'b1;      // idle plaintext = 1
                        key_bit   = seed_bit;           // key = scrambled ^ 1
                        plain_bit = in_bit ^ key_bit;   // = 1 (idle)
                        out_bit   <= plain_bit;
                        lfsr      <= {lfsr[9:0], seed_bit};
                        locked    <= 1'b0;
                        if (cnt == SEED_LEN[5:0] - 6'd1) begin
                            state <= S_VERIFY;
                            cnt   <= 6'd0;
                        end else begin
                            cnt <= cnt + 6'd1;
                        end
                    end

                    // ---- VERIFY: free-run, require idle (all-ones) window ----
                    S_VERIFY: begin
                        key_bit   = lfsr[8] ^ lfsr[10]; // key[n]=key[n-9]^key[n-11]
                        plain_bit = in_bit ^ key_bit;
                        out_bit   <= plain_bit;
                        lfsr      <= {lfsr[9:0], key_bit};
                        if (plain_bit != 1'b1) begin
                            // Bad phase guess: re-hunt from the next bit.
                            state <= S_HUNT;
                            cnt   <= 6'd0;
                        end else if (cnt == VERIFY_LEN[5:0] - 6'd1) begin
                            state  <= S_LOCKED;
                            locked <= 1'b1;
                        end else begin
                            cnt <= cnt + 6'd1;
                        end
                    end

                    // ---- LOCKED: LFSR free-runs, XOR-descramble the stream ----
                    S_LOCKED: begin
                        key_bit   = lfsr[8] ^ lfsr[10];
                        plain_bit = in_bit ^ key_bit;
                        out_bit   <= plain_bit;
                        lfsr      <= {lfsr[9:0], key_bit};
                        locked    <= 1'b1;
                    end

                    default: state <= S_HUNT;
                endcase
            end
        end
    end

endmodule
