// GENERATED by codegen/cmd/ifacegen — DO NOT EDIT. Source: codegen/ifacedef.
// iface sds1000cml-iface v1  build-ID 0xc2f6eb5f
//
// Register-decode include: per-register write-strobe wires + the read-data mux,
// generated from Access/Sem so the selector decode can NEVER drift from the
// schema (the exact bug class this codegen exists to kill). Hand RTL only assigns
// behavior behind the named wires — it never writes a selector case.
//
// `include this INSIDE the acq top module, AFTER `include "regs.vh". The top
// module must provide these signals:
//     we_commit          1-cycle "write accepted" pulse (GPMC write, synchronized)
//     wr_plane [7:0]     plane of the accepted write
//     wr_sel   [7:0]     selector of the accepted write
//     rd_plane [7:0]     plane of the current read
//     rd_sel   [7:0]     selector of the current read
//     rdata_<REG> [15:0] the read value the behavior drives, for each readable
//                        register whose read source is a hand-RTL wire (identity /
//                        build-ID / fixed-Expect regs are driven here, from the
//                        schema, and need no rdata_ wire).
// This include produces:
//     we_<REG>           1-cycle write strobe, one per writable register
//     rmux_rdata [15:0]  the muxed read value for {rd_plane, rd_sel}

// ---- write-strobe decode -------------------------------------------------
wire we_OPCODE = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_OPCODE);
wire we_RUN = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_RUN);
wire we_DECIM_LO = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_DECIM_LO);
wire we_DECIM_HI = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_DECIM_HI);
wire we_PRETRIG_LO = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_PRETRIG_LO);
wire we_PRETRIG_HI = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_PRETRIG_HI);
wire we_POSTTRIG_LO = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_POSTTRIG_LO);
wire we_POSTTRIG_HI = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_POSTTRIG_HI);
wire we_XFORM_CTRL = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_XFORM_CTRL);
wire we_ENV_COLS = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_ENV_COLS);
wire we_ENV_RESET = we_commit & (wr_plane == `PLANE_CS1) & (wr_sel == `SEL_ENV_RESET);
wire we_LED_LO = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LED_LO);
wire we_LED_HI = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LED_HI);
wire we_LED_STROBE = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LED_STROBE);
wire we_OFF_C1_LO = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_OFF_C1_LO);
wire we_OFF_C2_LO = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_OFF_C2_LO);
wire we_OFF_C1_HI = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_OFF_C1_HI);
wire we_OFF_C2_HI = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_OFF_C2_HI);
wire we_LVL_A_LO = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LVL_A_LO);
wire we_LVL_B_LO = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LVL_B_LO);
wire we_LVL_A_HI = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LVL_A_HI);
wire we_LVL_B_HI = we_commit & (wr_plane == `PLANE_CS3) & (wr_sel == `SEL_LVL_B_HI);

// ---- read-data mux -------------------------------------------------------
reg [15:0] rmux_rdata;
always @* begin
    rmux_rdata = 16'h0000;
    case ({rd_plane, rd_sel})
        { `PLANE_CS1, `SEL_BUILDID_LO }: rmux_rdata = `IFACE_BUILD_ID_LO; // buildid_lo
        { `PLANE_CS1, `SEL_BUILDID_HI }: rmux_rdata = `IFACE_BUILD_ID_HI; // buildid_hi
        { `PLANE_CS1, `SEL_VERSION }: rmux_rdata = 16'h0052; // const
        { `PLANE_CS1, `SEL_RUN }: rmux_rdata = rdata_RUN; // behavior
        { `PLANE_CS1, `SEL_DECIM_LO }: rmux_rdata = rdata_DECIM_LO; // behavior
        { `PLANE_CS1, `SEL_DECIM_HI }: rmux_rdata = rdata_DECIM_HI; // behavior
        { `PLANE_CS1, `SEL_PRETRIG_LO }: rmux_rdata = rdata_PRETRIG_LO; // behavior
        { `PLANE_CS1, `SEL_PRETRIG_HI }: rmux_rdata = rdata_PRETRIG_HI; // behavior
        { `PLANE_CS1, `SEL_POSTTRIG_LO }: rmux_rdata = rdata_POSTTRIG_LO; // behavior
        { `PLANE_CS1, `SEL_POSTTRIG_HI }: rmux_rdata = rdata_POSTTRIG_HI; // behavior
        { `PLANE_CS1, `SEL_BURST }: rmux_rdata = rdata_BURST; // behavior
        { `PLANE_CS1, `SEL_BURST_REMAIN }: rmux_rdata = rdata_BURST_REMAIN; // behavior
        { `PLANE_CS1, `SEL_STATUS_A }: rmux_rdata = rdata_STATUS_A; // behavior
        { `PLANE_CS1, `SEL_TRIGPOS_LO }: rmux_rdata = rdata_TRIGPOS_LO; // behavior
        { `PLANE_CS1, `SEL_TRIGPOS_HI }: rmux_rdata = rdata_TRIGPOS_HI; // behavior
        { `PLANE_CS1, `SEL_FILL }: rmux_rdata = rdata_FILL; // behavior
        { `PLANE_CS1, `SEL_XFORM_CTRL }: rmux_rdata = rdata_XFORM_CTRL; // behavior
        { `PLANE_CS1, `SEL_ENV_COLS }: rmux_rdata = rdata_ENV_COLS; // behavior
        { `PLANE_CS1, `SEL_ENV_DATA }: rmux_rdata = rdata_ENV_DATA; // behavior
        { `PLANE_CS1, `SEL_ENV_COUNT }: rmux_rdata = rdata_ENV_COUNT; // behavior
        { `PLANE_CS3, `SEL_CONF_DONE }: rmux_rdata = rdata_CONF_DONE; // behavior
        default: rmux_rdata = 16'h0000;
    endcase
end
