// GENERATED by codegen/cmd/ifacegen — DO NOT EDIT. Source: codegen/ifacedef.
// iface sds1000cml-iface v1  build-ID 0x4a9ccfa4
// stream: lane=18 stages=2 | capture: depth=20480 pretrig+mark
//
// Verilog-2001 `define macros (localparams at global scope are SystemVerilog-only,
// and a macro expands to a literal you cannot part-select). `include this header at
// global scope, then reference `SEL_X / `IFACE_BUILD_ID / `STATUS_A_DONE_MASK /
// `STATUS_A_DONE_LSB / `REC_DEPTH, etc.
`ifndef IFACE_REGS_VH
`define IFACE_REGS_VH

`define IFACE_BUILD_ID 32'h4a9ccfa4
`define IFACE_BUILD_ID_LO 16'hcfa4
`define IFACE_BUILD_ID_HI 16'h4a9c
`define PLANE_CS1 8'd1
`define PLANE_CS3 8'd3

// capture geometry — the single source of truth for the RTL, too: the circular
// writer derives REC_DEPTH / ADDR_W / PRETRIG_MAX from here (no Verilog module
// parameter to drift from the schema).
`define REC_DEPTH 20480
`define ADDR_W 15
`define PRETRIG_MAX 20478

// strobe payload opcodes — the app writes these 16-bit values to the named
// strobe register; the RTL compares the full write word against these macros,
// so app and fabric decode the same literal (folded into the build-ID).
`define OP_RESET 16'h0000  // OPCODE: idle the capture FSM
`define OP_GO 16'h0001  // OPCODE: arm / fast re-arm (honored only while RUN)
`define OP_HALT 16'h0002  // OPCODE: freeze the record

// ---- block meta (CS1 0x10+0x08) identity / build-ID handshake
// SEL_BUILDID_LO: R normal [CS1]
`define SEL_BUILDID_LO 8'h10
// SEL_BUILDID_HI: R normal [CS1]
`define SEL_BUILDID_HI 8'h11
// SEL_VERSION: R normal [CS1]
`define SEL_VERSION 8'h12

// ---- block capture (CS1 0x20+0x10) arm / halt / re-arm + stream decimation + programmable pre/post-trigger depth
// SEL_OPCODE: W strobe [CS1]
`define SEL_OPCODE 8'h20
// SEL_RUN: RW normal [CS1]
`define SEL_RUN 8'h21
`define RUN_MODE_MASK 16'h0003
`define RUN_MODE_LSB 5'd0
`define RUN_RUN_MASK 16'h0004
`define RUN_RUN_LSB 5'd2
// SEL_DECIM_LO: RW normal [CS1]
`define SEL_DECIM_LO 8'h22
// SEL_DECIM_HI: RW normal [CS1]
`define SEL_DECIM_HI 8'h23
// SEL_PRETRIG_LO: RW normal [CS1]
`define SEL_PRETRIG_LO 8'h24
// SEL_PRETRIG_HI: RW normal [CS1]
`define SEL_PRETRIG_HI 8'h25
// SEL_POSTTRIG_LO: RW normal [CS1]
`define SEL_POSTTRIG_LO 8'h26
// SEL_POSTTRIG_HI: RW normal [CS1]
`define SEL_POSTTRIG_HI 8'h27

// ---- block drain (CS1 0x30+0x10) frozen-record readout: a single fixed auto-inc BURST port (1-D DMA source) + remaining
// SEL_BURST: R auto-inc-port|read-after-halt [CS1]
`define SEL_BURST 8'h30
// SEL_BURST_REMAIN: R read-after-halt|level-status [CS1]
`define SEL_BURST_REMAIN 8'h3e
`define BURST_REMAIN_READY_MASK 16'h8000
`define BURST_REMAIN_READY_LSB 5'd15
`define BURST_REMAIN_REMAIN_MASK 16'h7fff
`define BURST_REMAIN_REMAIN_LSB 5'd0

// ---- block status (CS1 0x40+0x10) clean level acquisition status + interpolating trigger position + fill
// SEL_STATUS_A: R level-status [CS1]
`define SEL_STATUS_A 8'h41
`define STATUS_A_VALID_MASK 16'h0001
`define STATUS_A_VALID_LSB 5'd0
`define STATUS_A_TRIG_MASK 16'h0002
`define STATUS_A_TRIG_LSB 5'd1
`define STATUS_A_DONE_MASK 16'h0004
`define STATUS_A_DONE_LSB 5'd2
// SEL_TRIGPOS_LO: R read-after-halt|level-status [CS1]
`define SEL_TRIGPOS_LO 8'h42
`define TRIGPOS_LO_FRAC_MASK 16'hffff
`define TRIGPOS_LO_FRAC_LSB 5'd0
// SEL_TRIGPOS_HI: R read-after-halt|level-status [CS1]
`define SEL_TRIGPOS_HI 8'h43
`define TRIGPOS_HI_IDX_MASK 16'h7fff
`define TRIGPOS_HI_IDX_LSB 5'd0
// SEL_FILL: R level-status [CS1]
`define SEL_FILL 8'h44
`define FILL_COUNT_MASK 16'h07ff
`define FILL_COUNT_LSB 5'd0

// ---- block spine (CS1 0x50+0x10) streaming-spine control: transform-stage bypass + envelope config
// SEL_XFORM_CTRL: RW normal [CS1]
`define SEL_XFORM_CTRL 8'h50
`define XFORM_CTRL_BYPASS0_MASK 16'h0001
`define XFORM_CTRL_BYPASS0_LSB 5'd0
`define XFORM_CTRL_BYPASS1_MASK 16'h0002
`define XFORM_CTRL_BYPASS1_LSB 5'd1
// SEL_ENV_COLS: RW normal [CS1]
`define SEL_ENV_COLS 8'h51

// ---- block channels (CS1 0x60+0x20) result/event channel ports (the uniform DATA/COUNT/RESET triad); envelope is the first instance of the reusable result_fifo contract
// SEL_ENV_DATA: R auto-inc-port|read-after-halt [CS1]
`define SEL_ENV_DATA 8'h60
// SEL_ENV_COUNT: R level-status [CS1]
`define SEL_ENV_COUNT 8'h61
`define ENV_COUNT_COUNT_MASK 16'h7fff
`define ENV_COUNT_COUNT_LSB 5'd0
`define ENV_COUNT_OVERFLOW_MASK 16'h8000
`define ENV_COUNT_OVERFLOW_LSB 5'd15
// SEL_ENV_RESET: W strobe [CS1]
`define SEL_ENV_RESET 8'h62

// ---- block trigger (CS1 0x80+0x20) RESERVED (v1): HW trigger-discrimination taps — no registers yet

// ---- block measure (CS1 0xa0+0x20) RESERVED (v1): HW measurement result ports — no registers yet

// ---- block decode (CS1 0xc0+0x20) RESERVED (v2): serial-decode result ports — no registers yet

// ---- block config (CS3 0x00+0x09) config plane: nCONFIG / CONF_DONE (NEVER written by the app)
// SEL_CONF_DONE: R level-status [CS3]
`define SEL_CONF_DONE 8'h07
`define CONF_DONE_DONE_MASK 16'h0080
`define CONF_DONE_DONE_LSB 5'd7

// ---- block frontend (CS3 0x09+0x37) analog front-end writes: LED latch, per-channel offset DACs, trigger-level DAC (hi write self-latches + loads the serializer)
// SEL_LED_LO: W normal [CS3]
`define SEL_LED_LO 8'h09
// SEL_LED_HI: W normal [CS3]
`define SEL_LED_HI 8'h0a
// SEL_LED_STROBE: W strobe [CS3]
`define SEL_LED_STROBE 8'h0b
// SEL_OFF_C1_LO: W normal [CS3]
`define SEL_OFF_C1_LO 8'h10
// SEL_OFF_C2_LO: W normal [CS3]
`define SEL_OFF_C2_LO 8'h11
// SEL_OFF_C1_HI: W normal [CS3]
`define SEL_OFF_C1_HI 8'h30
// SEL_OFF_C2_HI: W normal [CS3]
`define SEL_OFF_C2_HI 8'h31
// SEL_LVL_A_LO: W normal [CS3]
`define SEL_LVL_A_LO 8'h14
// SEL_LVL_B_LO: W normal [CS3]
`define SEL_LVL_B_LO 8'h15
// SEL_LVL_A_HI: W strobe [CS3]
`define SEL_LVL_A_HI 8'h34
// SEL_LVL_B_HI: W strobe [CS3]
`define SEL_LVL_B_HI 8'h35

`endif
