// Package emit renders a validated schema.Interface into the four generated
// artifacts: the Verilog register header (regs.vh), the Verilog decode include
// (regmux.vh), the app's Go bindings (iface.go) and the register-map reference
// (REGISTER-MAP.md). Plain string building, declaration order everywhere, so
// the output is byte-stable and the drift gate is meaningful.
package emit

import (
	"fmt"
	"strings"

	"open-sds/codegen/schema"
)

// Banner is the first line of every generated file (after the comment lead-in).
const Banner = "GENERATED by codegen/cmd/ifacegen from codegen/ifacedef; DO NOT EDIT. Edit the schema, run `make generate` in codegen/."

// BuildIDNote documents the fingerprint so a reader of any artifact knows what moves it.
const BuildIDNote = "build-ID = FNV-1a 64-bit over schema.Interface.Canonical() folded to 32 bits (hi32 XOR lo32); every structural schema change (selectors, access, fields, enums, stubs, opcodes, DIAG layout, geometry, identity values) moves it, Desc text does not"

func check(i schema.Interface) error {
	if errs := i.Validate(); len(errs) > 0 {
		return fmt.Errorf("schema %s v%d is invalid:\n  %s", i.Name, i.Version, strings.Join(errs, "\n  "))
	}
	return nil
}

func lo16(v uint32) uint16 { return uint16(v & 0xffff) }
func hi16(v uint32) uint16 { return uint16(v >> 16) }

// camel turns UPPER_SNAKE into CamelCase (BURST_REMAIN -> BurstRemain, E1E2 -> E1e2).
func camel(s string) string {
	var b strings.Builder
	up := true
	for _, c := range s {
		switch {
		case c == '_':
			up = true
		case up:
			b.WriteRune(c)
			up = false
		case c >= 'A' && c <= 'Z':
			b.WriteRune(c + ('a' - 'A'))
		default:
			b.WriteRune(c)
		}
	}
	return b.String()
}

// fieldSummary renders "MODE[1:0] RUN[2]" for the doc tables.
func fieldSummary(fs []schema.Field) string {
	var parts []string
	for _, f := range fs {
		if f.Hi == f.Lo {
			parts = append(parts, fmt.Sprintf("%s[%d]", f.Name, f.Lo))
		} else {
			parts = append(parts, fmt.Sprintf("%s[%d:%d]", f.Name, f.Hi, f.Lo))
		}
	}
	return strings.Join(parts, " ")
}

func accessDoc(r schema.Register) string {
	s := r.Access.String()
	if r.Pop {
		s += " pop"
	}
	if r.Strobe {
		s += " strobe"
	}
	if r.Stub {
		s += " stub"
	}
	return s
}

func diagAccessDoc(d schema.DiagEntry) string {
	s := d.Access.String()
	if d.Stub {
		s += " stub"
	}
	return s
}

// selMaskDoc describes a selector mask by the GPMC address lines it decodes:
// selector bit b is GPMC A(b+1) (the 16-bit bus has no A0).
func selMaskDoc(mask uint8) string {
	var dec, masked []string
	for b := 0; b < 8; b++ {
		if mask&(1<<b) != 0 {
			dec = append(dec, fmt.Sprintf("A%d", b+1))
		} else {
			masked = append(masked, fmt.Sprint(b))
		}
	}
	s := "decodes GPMC " + strings.Join(dec, ",")
	if len(masked) > 0 {
		s += "; selector bit(s) " + strings.Join(masked, ",") + " ignored"
	}
	return s
}

// selList renders selectors as "0x21, 0x57".
func selList(sels []uint8) string {
	var parts []string
	for _, s := range sels {
		parts = append(parts, fmt.Sprintf("0x%02x", s))
	}
	return strings.Join(parts, ", ")
}
