// Package emit turns a validated schema.Interface into the generated artifacts —
// the Verilog register header (regs.vh), the Verilog decode include (regmux.vh),
// the app's Go bindings (iface.go), and the register-map doc — by rendering
// readable text/template sources over a flattened, precomputed view (view.go).
//
// This replaces the proving-ground's line-by-line fmt.Fprintf emitters: the
// templates carry the shape, view.go carries the arithmetic, and the Go output
// is run through go/format so regeneration is byte-stable (the drift gate). All
// rendering iterates slices only, so output order is deterministic.
package emit

import (
	"embed"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"open-sds/codegen/schema"
)

const genBanner = "GENERATED by codegen/cmd/ifacegen — DO NOT EDIT. Source: codegen/ifacedef."

//go:embed templates/*.tmpl
var templatesFS embed.FS

// funcs is the shared FuncMap the templates draw on. Most hex/mask work is
// precomputed in view.go; these keep the remaining template call sites readable.
var funcs = template.FuncMap{
	"hex8":  func(v any) string { return fmt.Sprintf("%02x", asU64(v)) },
	"hex16": func(v any) string { return fmt.Sprintf("%04x", asU64(v)) },
	"hex32": func(v any) string { return fmt.Sprintf("%08x", asU64(v)) },
	"upper": strings.ToUpper,
	// md escapes text for a Markdown table cell (pipes and newlines).
	"md": func(s string) string {
		return strings.NewReplacer("|", "\\|", "\n", " ").Replace(s)
	},
	"mask": func(hi, lo uint) string {
		var m uint16
		for b := lo; b <= hi; b++ {
			m |= 1 << b
		}
		return fmt.Sprintf("%04x", m)
	},
}

var tmpl = template.Must(template.New("codegen").Funcs(funcs).ParseFS(templatesFS, "templates/*.tmpl"))

func render(name string, i schema.Interface) (string, error) {
	var b strings.Builder
	if err := tmpl.ExecuteTemplate(&b, name, newView(i)); err != nil {
		return "", fmt.Errorf("render %s: %w", name, err)
	}
	return b.String(), nil
}

// Verilog renders regs.vh: selector params, plane params, field mask/LSB macros,
// the build-ID (and its 16-bit halves), and the capture geometry.
func Verilog(i schema.Interface) (string, error) { return render("regs.vh.tmpl", i) }

// Regmux renders regmux.vh: the per-register write-strobe wires and the read-data
// mux, derived from Access/Sem so the selector decode can never drift.
func Regmux(i schema.Interface) (string, error) { return render("regmux.vh.tmpl", i) }

// Doc renders the register-map reference (Markdown).
func Doc(i schema.Interface) (string, error) { return render("register-map.md.tmpl", i) }

// GoBindings renders the app's iface package and runs it through go/format so
// regeneration is byte-identical (the drift gate depends on this).
func GoBindings(i schema.Interface) (string, error) {
	s, err := render("bindings.go.tmpl", i)
	if err != nil {
		return "", err
	}
	out, err := format.Source([]byte(s))
	if err != nil {
		return s, fmt.Errorf("gofmt generated bindings: %w", err)
	}
	return string(out), nil
}

func asU64(v any) uint64 {
	switch x := v.(type) {
	case uint:
		return uint64(x)
	case uint8:
		return uint64(x)
	case uint16:
		return uint64(x)
	case uint32:
		return uint64(x)
	case uint64:
		return x
	case int:
		return uint64(x)
	default:
		return 0
	}
}
