// ENGMODEL-OWNER-UNIT: FU-CODEGEN-EMIT
package emit

import (
	_ "embed"
	"fmt"
	"go/format"
	"strings"

	"open-sds/codegen/schema"
)

// wordfmtSrc is the source of the word-format models (codegen/emit/wordfmt),
// spliced verbatim into iface.go so the app and rung R2b compare drained words
// against exactly the code that is unit-tested here.
//
//go:embed wordfmt/wordfmt.go
var wordfmtSrc string

// spliceGoSource strips the package clause, everything before it (the package
// comment) and the import declaration from a single-file package whose only
// permitted import is "fmt" (iface.go imports it already), returning the
// declarations to append to the bindings.
// TRLC-LINKS: REQ-SDS-157, REQ-SDS-159
func spliceGoSource(src string) (string, error) {
	_, rest, ok := strings.Cut("\n"+src, "\npackage ")
	if !ok {
		return "", fmt.Errorf("no package clause")
	}
	_, rest, ok = strings.Cut(rest, "\n")
	if !ok {
		return "", fmt.Errorf("nothing after the package clause")
	}
	rest = strings.TrimLeft(rest, "\n")
	switch {
	case strings.HasPrefix(rest, "import \"fmt\"\n"):
		rest = strings.TrimPrefix(rest, "import \"fmt\"\n")
	case strings.HasPrefix(rest, "import"):
		return "", fmt.Errorf("the spliced source may import \"fmt\" only, has %q", strings.SplitN(rest, "\n", 2)[0])
	}
	if strings.Contains(rest, "\nimport ") {
		return "", fmt.Errorf("the spliced source has a second import declaration")
	}
	return strings.TrimLeft(rest, "\n"), nil
}

// GoBindings renders app/internal/iface/iface.go.
// TRLC-LINKS: REQ-SDS-157, REQ-SDS-159
func GoBindings(i schema.Interface) (string, error) {
	if err := check(i); err != nil {
		return "", err
	}
	models, err := spliceGoSource(wordfmtSrc)
	if err != nil {
		return "", fmt.Errorf("wordfmt splice: %w", err)
	}
	id := i.BuildID()
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	p("// Code generated by codegen/cmd/ifacegen; DO NOT EDIT.\n// %s\n\n", Banner)
	p("// Package iface is the app's view of the %s v%d fabric interface:\n", i.Name, i.Version)
	p("// selectors, field masks/shifts and enum values, identity values, opcodes, DIAG\n")
	p("// window indices, the register tables for tooling, and the Go models of every\n")
	p("// drained word format (Model*, the rung R2b reference). The engine drives the\n")
	p("// fabric through these — never through hand-packed selectors or masks.\n")
	p("package iface\n\nimport \"fmt\"\n\n")

	g := i.Geometry
	p("// Identity. BuildID (schema + RTL source digest 0x%08x) is read back through BUILDID_LO/HI;\n// the app refuses (reloads) a fabric whose build-ID differs. %s.\n", i.SourceDigest, BuildIDNote)
	p("const (\n\tName = %q\n\tVersion uint16 = %d\n\tBuildID uint32 = 0x%08x\n\tBuildIDLo uint16 = 0x%04x\n\tBuildIDHi uint16 = 0x%04x\n",
		i.Name, i.Version, id, lo16(id), hi16(id))
	p("\tVersionMagic uint16 = 0x%04x // value of VERSION\n\tFabricID uint16 = 0x%04x // value of FABRIC_ID\n", i.VersionMagic, i.FabricID)
	p("\tSelMask uint16 = 0x%02x // selector bits the fabric decodes: %s\n", i.SelMask, selMaskDoc(i.SelMask))
	p("\tSelCount = %d // distinct selectors\n", i.SelCount())
	if i.Legacy.Version != 0 {
		p("\tSelMaskV%d uint16 = 0x%02x // the v%d generation's mask; its registers keep those selectors\n", i.Legacy.Version, i.Legacy.SelMask, i.Legacy.Version)
	}
	p(")\n\n")
	p("// Record geometry (06-TIERS §1.1, §1.3, §1.4): the record is Rows rows of RowCols words,\n")
	p("// drained row-major / column-minor; the stack delay line holds DlineRows rows and an\n")
	p("// accumulator cell is AccBits wide, so StackNMax records never overflow it.\n")
	p("const (\n\tRecDepth = %d\n\tAddrW = %d\n\tPretrigMax = %d\n\tRowCols = %d\n\tRows = %d\n\tDlineRows = %d\n\tAccBits = %d\n\tStackNMax = %d\n)\n\n",
		g.RecDepth, g.AddrW, g.PretrigMax(), g.RowCols, g.Rows, g.DlineRows, g.AccBits, g.StackNMax)

	p("// Selectors — pass unshifted; the bus driver applies the byte-address shift.\nconst (\n")
	for _, r := range i.Regs {
		p("\tSel%s uint16 = 0x%02x // %s: %s\n", camel(r.Name), r.Sel, accessDoc(r), r.Desc)
	}
	p(")\n\n")

	p("// %s opcodes (write the value to Sel%s; any other value is ignored by the fabric).\nconst (\n", i.OpcodeReg, camel(i.OpcodeReg))
	for _, o := range i.Opcodes {
		p("\tOp%s uint16 = 0x%04x // %s\n", camel(o.Name), o.Value, o.Desc)
	}
	p(")\n\n")

	enums := func(prefix string, fs []schema.Field) {
		for _, f := range fs {
			for _, e := range f.Enum {
				p("\t%s%s%s uint16 = %d // %s.%s: %s\n", prefix, camel(f.Name), camel(e.Name), e.Value, prefix, f.Name, e.Desc)
			}
		}
	}
	p("// Register fields: <Reg><Field>Mask / <Reg><Field>Shift.\nconst (\n")
	for _, r := range i.Regs {
		for _, f := range r.Fields {
			n := camel(r.Name) + camel(f.Name)
			p("\t%sMask uint16 = 0x%04x // %s\n\t%sShift = %d\n", n, f.Mask(), f.Desc, n, f.Lo)
		}
	}
	p(")\n\n")
	p("// Field values: <Reg><Field><Name> (unshifted; put them with Field.Put or << Shift).\nconst (\n")
	for _, r := range i.Regs {
		enums(camel(r.Name), r.Fields)
	}
	p(")\n\n")

	p("// DIAG window indices (write to Sel%s, then access Sel%s).\nconst (\n", camel(i.DiagIdxReg), camel(i.DiagDataReg))
	for _, d := range i.Diag {
		if d.Count == 1 {
			p("\tDiag%s uint16 = 0x%02x // %s: %s\n", camel(d.Name), d.Idx, diagAccessDoc(d), d.Desc)
		} else {
			n := camel(d.Name)
			p("\tDiag%sBase uint16 = 0x%02x // %s: %s\n\tDiag%sCount = %d\n\tDiag%sLast uint16 = 0x%02x\n", n, d.Idx, diagAccessDoc(d), d.Desc, n, d.Count, n, d.Last())
		}
	}
	p("\tDiagReservedBase uint16 = 0x%02x\n)\n\n", i.DiagReserved)

	p("// DIAG window fields: Diag<Entry><Field>Mask / Shift.\nconst (\n")
	for _, d := range i.Diag {
		for _, f := range d.Fields {
			n := "Diag" + camel(d.Name) + camel(f.Name)
			p("\t%sMask uint16 = 0x%04x // %s\n\t%sShift = %d\n", n, f.Mask(), f.Desc, n, f.Lo)
		}
	}
	p(")\n\n")
	p("// DIAG window field values: Diag<Entry><Field><Name>.\nconst (\n")
	for _, d := range i.Diag {
		enums("Diag"+camel(d.Name), d.Fields)
	}
	p(")\n\n")

	p(`// Access is the read/write capability of a register.
type Access uint8

const (
	AccR  Access = 1
	AccW  Access = 2
	AccRW Access = 3
)

func (a Access) CanRead() bool  { return a&AccR != 0 }
func (a Access) CanWrite() bool { return a&AccW != 0 }
func (a Access) String() string {
	switch a {
	case AccR:
		return "R"
	case AccW:
		return "W"
	case AccRW:
		return "RW"
	}
	return fmt.Sprintf("Access(%%d)", uint8(a))
}

// EnumValue is a named value of a field.
type EnumValue struct {
	Name  string
	Value uint16
	Desc  string
}

// Field is a named bit range of a 16-bit word.
type Field struct {
	Name  string
	Mask  uint16
	Shift uint8
	Enum  []EnumValue // named values, if any (unshifted)
	Desc  string
}

// Get extracts the field from word.
func (f Field) Get(word uint16) uint16 { return (word & f.Mask) >> f.Shift }

// Put returns word with the field replaced by v (v is masked to the field width).
func (f Field) Put(word, v uint16) uint16 { return (word &^ f.Mask) | ((v << f.Shift) & f.Mask) }

// ValueName returns the enum name of the field's value in word ("" if unnamed).
func (f Field) ValueName(word uint16) string {
	v := f.Get(word)
	for _, e := range f.Enum {
		if e.Value == v {
			return e.Name
		}
	}
	return ""
}

// Register describes one selector of the map.
type Register struct {
	Name       string
	Sel        uint16
	Since      uint16 // schema version that introduced it
	Access     Access
	Pop        bool   // pop-on-read port: every read advances the source
	Strobe     bool   // write strobe: the written word is decoded, nothing is stored
	Const      bool   // read value is the fixed ConstValue
	ConstValue uint16
	AliasOf    string // read alias of another register (shares its pop)
	Stub       bool   // not implemented by this fabric increment: reads 0, writes ignored
	Fields     []Field
	Desc       string
}

// DiagEntry describes one index (or Count consecutive indices) of the DIAG window.
type DiagEntry struct {
	Name   string
	Idx    uint16
	Count  int
	Access Access
	Stub   bool // not implemented by this fabric increment: reads 0, writes ignored
	Fields []Field
	Desc   string
}

// Opcode is one accepted payload of the opcode strobe register.
type Opcode struct {
	Name  string
	Value uint16
	Desc  string
}

// MaskSel reduces a selector to the bits the fabric decodes.
func MaskSel(sel uint16) uint16 { return sel & SelMask }

// Registers returns the register table in declaration order (a fresh copy).
func Registers() []Register { return append([]Register(nil), registers...) }

// BySel returns the register decoded at sel (after MaskSel).
func BySel(sel uint16) (Register, bool) {
	sel = MaskSel(sel)
	for _, r := range registers {
		if r.Sel == sel {
			return r, true
		}
	}
	return Register{}, false
}

// ByName returns the register called name.
func ByName(name string) (Register, bool) {
	for _, r := range registers {
		if r.Name == name {
			return r, true
		}
	}
	return Register{}, false
}

// Undecoded returns the selectors the contract keeps undecoded (read 0, writes
// ignored; the vendor arm/halt words), a fresh copy.
func Undecoded() []uint16 { return append([]uint16(nil), undecoded...) }

// IsUndecoded reports whether sel (after MaskSel) is one of them.
func IsUndecoded(sel uint16) bool {
	sel = MaskSel(sel)
	for _, u := range undecoded {
		if u == sel {
			return true
		}
	}
	return false
}

// DiagWindow returns the DIAG window table in index order (a fresh copy).
func DiagWindow() []DiagEntry { return append([]DiagEntry(nil), diagWindow...) }

// Opcodes returns the opcode table (a fresh copy).
func Opcodes() []Opcode { return append([]Opcode(nil), opcodes...) }

// CheckIdentity compares the four identity words read from a fabric against this
// interface and returns a descriptive error on the first mismatch (fabric-ID,
// then version magic, then build-ID). A nil error means the fabric is the one
// this package was generated for.
func CheckIdentity(buildLo, buildHi, version, fabric uint16) error {
	if fabric != FabricID {
		return fmt.Errorf("iface: FABRIC_ID 0x%%04x, want 0x%%04x (not the %s image)", fabric, FabricID)
	}
	if version != VersionMagic {
		return fmt.Errorf("iface: VERSION 0x%%04x, want 0x%%04x", version, VersionMagic)
	}
	if got := uint32(buildHi)<<16 | uint32(buildLo); got != BuildID {
		return fmt.Errorf("iface: build-ID 0x%%08x, want 0x%%08x (mispaired fabric/app build)", got, BuildID)
	}
	return nil
}

`, i.Name)

	fields := func(fs []schema.Field) string {
		if len(fs) == 0 {
			return "nil"
		}
		var s strings.Builder
		s.WriteString("[]Field{")
		for k, f := range fs {
			if k > 0 {
				s.WriteString(", ")
			}
			fmt.Fprintf(&s, "{Name: %q, Mask: 0x%04x, Shift: %d, Desc: %q", f.Name, f.Mask(), f.Lo, f.Desc)
			if len(f.Enum) > 0 {
				s.WriteString(", Enum: []EnumValue{")
				for j, e := range f.Enum {
					if j > 0 {
						s.WriteString(", ")
					}
					fmt.Fprintf(&s, "{%q, %d, %q}", e.Name, e.Value, e.Desc)
				}
				s.WriteString("}")
			}
			s.WriteString("}")
		}
		s.WriteString("}")
		return s.String()
	}
	p("var registers = []Register{\n")
	for _, r := range i.Regs {
		p("\t{Name: %q, Sel: Sel%s, Since: %d, Access: Acc%s, Pop: %t, Strobe: %t, Const: %t, ConstValue: 0x%04x, AliasOf: %q, Stub: %t, Fields: %s, Desc: %q},\n",
			r.Name, camel(r.Name), r.Since, r.Access, r.Pop, r.Strobe, r.Source == schema.SrcConst, r.Const, r.AliasOf, r.Stub, fields(r.Fields), r.Desc)
	}
	p("}\n\nvar undecoded = []uint16{")
	for k, u := range i.Undecoded {
		if k > 0 {
			p(", ")
		}
		p("0x%02x", u)
	}
	p("}\n\nvar diagWindow = []DiagEntry{\n")
	for _, d := range i.Diag {
		p("\t{Name: %q, Idx: 0x%02x, Count: %d, Access: Acc%s, Stub: %t, Fields: %s, Desc: %q},\n", d.Name, d.Idx, d.Count, d.Access, d.Stub, fields(d.Fields), d.Desc)
	}
	p("}\n\nvar opcodes = []Opcode{\n")
	for _, o := range i.Opcodes {
		p("\t{%q, Op%s, %q},\n", o.Name, camel(o.Name), o.Desc)
	}
	p("}\n\n")

	p("// ---- word-format models: spliced from codegen/emit/wordfmt/wordfmt.go (tested there) ----\n\n")
	b.WriteString(models)

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt of the generated bindings failed: %w\n%s", err, b.String())
	}
	return string(out), nil
}
