// GENERATED by codegen/cmd/ifacegen from codegen/ifacedef; DO NOT EDIT. Edit the schema, run `make generate` in codegen/.
// iface sds1000cml-default v3  build-ID 0x6af8705a
//
// Register-decode include. `include it INSIDE the top module, AFTER regs.vh.
// The top module provides:
//     we_commit          1-cycle "write accepted" pulse (nWE rising, data + sel settled)
//     wr_sel   [7:0]     selector of the accepted write, raw: bit b = GPMC A(b+1) as it
//                        reaches the fabric; bits outside SEL_MASK are masked here
//     wr_data  [15:0]    the written word (used by the strobe decodes below)
//     rd_pop   [1]       1-cycle "read completed" pulse (nOE rising) for pop-on-read ports
//     rd_sel   [7:0]     selector of the current read (raw; masked here)
//     rdata_<REG> [15:0] the read value the behaviour drives, one per readable register
//                        whose source is hand RTL (identity / build-ID / constant registers
//                        are driven from the schema here and need no rdata_ wire; stub
//                        registers read 0 here and need none either)
// This include produces:
//     rmux_wr_sel / rmux_rd_sel [7:0]  the masked selectors (sel & SEL_MASK)
//     we_<REG>            1-cycle write strobe, one per writable non-stub register
//     op_<NAME>           1-cycle strobe per opcode of the opcode register
//     pop_<REG>           1-cycle pop strobe, one per pop-on-read register (its aliases included)
//     rmux_rdata [15:0]   the read value for rmux_rd_sel (0 for undecoded and stub selectors)

// ---- selector masking: SEL_MASK 0x7f decodes GPMC A1,A2,A3,A4,A5,A6,A7; selector bit(s) 7 ignored ------------------
// bits 1:0 are GPMC A2/A1 (balls A2/B1): the slave presents them in sel[1:0].
wire [7:0] rmux_wr_sel = wr_sel & `SEL_MASK;
wire [7:0] rmux_rd_sel = rd_sel & `SEL_MASK;
// undecoded by contract (read 0, writes ignored): 0x21, 0x57

// ---- write strobes (stub registers — not implemented in this increment — get none) ----
wire we_DIAG_IDX = we_commit & (rmux_wr_sel == `SEL_DIAG_IDX);
wire we_DIAG_DATA = we_commit & (rmux_wr_sel == `SEL_DIAG_DATA);
wire we_OPCODE = we_commit & (rmux_wr_sel == `SEL_OPCODE);
wire we_RUN = we_commit & (rmux_wr_sel == `SEL_RUN);
wire we_DECIM_LO = we_commit & (rmux_wr_sel == `SEL_DECIM_LO);
wire we_DECIM_HI = we_commit & (rmux_wr_sel == `SEL_DECIM_HI);
wire we_PRETRIG_LO = we_commit & (rmux_wr_sel == `SEL_PRETRIG_LO);
wire we_PRETRIG_HI = we_commit & (rmux_wr_sel == `SEL_PRETRIG_HI);
wire we_POSTTRIG_LO = we_commit & (rmux_wr_sel == `SEL_POSTTRIG_LO);
wire we_POSTTRIG_HI = we_commit & (rmux_wr_sel == `SEL_POSTTRIG_HI);
wire we_ACQ_CTRL = we_commit & (rmux_wr_sel == `SEL_ACQ_CTRL);
wire we_TRIG_LEVEL = we_commit & (rmux_wr_sel == `SEL_TRIG_LEVEL);
wire we_DIAG_CTRL = we_commit & (rmux_wr_sel == `SEL_DIAG_CTRL);
wire we_IL_CTRL = we_commit & (rmux_wr_sel == `SEL_IL_CTRL);
// DEC_RECIP: stub, writes ignored
// DEC_PRE: stub, writes ignored
wire we_DRAIN_START = we_commit & (rmux_wr_sel == `SEL_DRAIN_START);
wire we_DRAIN_LEN = we_commit & (rmux_wr_sel == `SEL_DRAIN_LEN);
// STACK_N: stub, writes ignored
// STACK_CTRL: stub, writes ignored
// STACK_PRE: stub, writes ignored
// STACK_LEN: stub, writes ignored
// EYE_CTRL: stub, writes ignored

// ---- OPCODE opcode strobes (full-word compare; any other value is ignored) ----
wire op_RESET = we_OPCODE & (wr_data == `OP_RESET);
wire op_GO = we_OPCODE & (wr_data == `OP_GO);
wire op_HALT = we_OPCODE & (wr_data == `OP_HALT);
wire op_REWIND = we_OPCODE & (wr_data == `OP_REWIND);
wire op_STACK_CLEAR = we_OPCODE & (wr_data == `OP_STACK_CLEAR);

// ---- pop-on-read strobes ---------------------------------------------------------
wire pop_BURST = rd_pop & ((rmux_rd_sel == `SEL_BURST) | (rmux_rd_sel == `SEL_BURST_ALIAS));
wire pop_SNAP_POP = rd_pop & ((rmux_rd_sel == `SEL_SNAP_POP));
wire pop_ENV_DATA = rd_pop & ((rmux_rd_sel == `SEL_ENV_DATA));

// ---- read-data mux ----------------------------------------------------------------
reg [15:0] rmux_rdata;
always @* begin
    case (rmux_rd_sel)
        `SEL_BURST_ALIAS: rmux_rdata = rdata_BURST; // alias of BURST
        `SEL_CLK_STAT: rmux_rdata = rdata_CLK_STAT;
        `SEL_DIAG_IDX: rmux_rdata = rdata_DIAG_IDX;
        `SEL_DIAG_DATA: rmux_rdata = rdata_DIAG_DATA;
        `SEL_BUILDID_LO: rmux_rdata = `IFACE_BUILD_ID_LO;
        `SEL_BUILDID_HI: rmux_rdata = `IFACE_BUILD_ID_HI;
        `SEL_VERSION: rmux_rdata = 16'h00a3; // constant
        `SEL_FABRIC_ID: rmux_rdata = 16'ha2f1; // constant
        `SEL_RUN: rmux_rdata = rdata_RUN;
        `SEL_DECIM_LO: rmux_rdata = rdata_DECIM_LO;
        `SEL_DECIM_HI: rmux_rdata = rdata_DECIM_HI;
        `SEL_PRETRIG_LO: rmux_rdata = rdata_PRETRIG_LO;
        `SEL_PRETRIG_HI: rmux_rdata = rdata_PRETRIG_HI;
        `SEL_POSTTRIG_LO: rmux_rdata = rdata_POSTTRIG_LO;
        `SEL_POSTTRIG_HI: rmux_rdata = rdata_POSTTRIG_HI;
        `SEL_BURST: rmux_rdata = rdata_BURST;
        `SEL_BURST_REMAIN: rmux_rdata = rdata_BURST_REMAIN;
        `SEL_STATUS_A: rmux_rdata = rdata_STATUS_A;
        `SEL_TRIGPOS_LO: rmux_rdata = rdata_TRIGPOS_LO;
        `SEL_TRIGPOS_HI: rmux_rdata = rdata_TRIGPOS_HI;
        `SEL_FILL: rmux_rdata = rdata_FILL;
        `SEL_ACQ_CTRL: rmux_rdata = rdata_ACQ_CTRL;
        `SEL_TRIG_LEVEL: rmux_rdata = rdata_TRIG_LEVEL;
        `SEL_SNOOP_SEL: rmux_rdata = rdata_SNOOP_SEL;
        `SEL_SNOOP_DATA: rmux_rdata = rdata_SNOOP_DATA;
        `SEL_DIAG_CTRL: rmux_rdata = rdata_DIAG_CTRL;
        `SEL_SNAP_REMAIN: rmux_rdata = rdata_SNAP_REMAIN;
        `SEL_SNAP_POP: rmux_rdata = rdata_SNAP_POP;
        `SEL_MISC_RD: rmux_rdata = rdata_MISC_RD;
        `SEL_ENV_DATA: rmux_rdata = rdata_ENV_DATA;
        `SEL_DBG: rmux_rdata = rdata_DBG;
        `SEL_IL_CTRL: rmux_rdata = rdata_IL_CTRL;
        `SEL_DEC_RECIP: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_DEC_PRE: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_DRAIN_START: rmux_rdata = rdata_DRAIN_START;
        `SEL_DRAIN_LEN: rmux_rdata = rdata_DRAIN_LEN;
        `SEL_DRAIN_STAT: rmux_rdata = rdata_DRAIN_STAT;
        `SEL_POP_MON: rmux_rdata = rdata_POP_MON;
        `SEL_STACK_N: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_STACK_CTRL: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_STACK_CNT: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_STACK_PRE: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_STACK_LEN: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_STATUS_B: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_EYE_CTRL: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_EYE_CNT: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        `SEL_DBG2: rmux_rdata = 16'h0000; // stub: reads 0 in this increment
        default: rmux_rdata = 16'h0000;
    endcase
end
