// GENERATED by codegen/cmd/ifacegen from codegen/ifacedef; DO NOT EDIT. Edit the schema, run `make generate` in codegen/.
// iface sds1000cml-default v3  build-ID 0x6af8705a
// build-ID = FNV-1a 64-bit over schema.Interface.Canonical() folded to 32 bits (hi32 XOR lo32); every structural schema change (selectors, access, fields, enums, stubs, opcodes, DIAG layout, geometry, identity values) moves it, Desc text does not
//
// Verilog-2001 `define macros (a localparam at global scope is SystemVerilog-only).
// `include this header at global scope, then use `SEL_<REG>, `<REG>_<FIELD>_MASK,
// `<REG>_<FIELD>_LSB, `<REG>_<FIELD>_<ENUM>, `OP_<NAME>, `DIAG_<NAME>, `REC_DEPTH, `ROW_COLS, `IFACE_BUILD_ID ...
`ifndef IFACE_REGS_VH
`define IFACE_REGS_VH

// ---- identity ------------------------------------------------------------
`define IFACE_NAME "sds1000cml-default"
`define IFACE_VERSION 16'd3
`define IFACE_BUILD_ID 32'h6af8705a
`define IFACE_BUILD_ID_LO 16'h705a
`define IFACE_BUILD_ID_HI 16'h6af8
`define VERSION_MAGIC 16'h00a3
`define FABRIC_ID 16'ha2f1
`define SEL_MASK 8'h7f  // selector bits the fabric decodes (128 selectors): decodes GPMC A1,A2,A3,A4,A5,A6,A7; selector bit(s) 7 ignored
`define SEL_MASK_V2 8'h7c  // the v2 generation's mask: its registers keep those selectors
// undecoded selectors (read 0, writes ignored; no register may take them): 0x21, 0x57

// ---- record geometry (the writers/readers derive from these, no module parameter to drift) ----
`define REC_DEPTH 20480
`define ADDR_W 15
`define PRETRIG_MAX 20478
`define ROW_COLS 5  // words per row; the reader emits row-major, column-minor
`define ROWS 4096  // rows of the record (REC_DEPTH / ROW_COLS)
`define DLINE_ROWS 512  // stack delay line / snapshot rows
`define ACC_BITS 18  // stack accumulator cell width
`define STACK_N_MAX 1024  // records per stack batch without overflow

// ---- OPCODE strobe payloads (the RTL compares the whole write word; other values are ignored) ----
`define OP_RESET 16'h0000  // return to idle, clear the record
`define OP_GO 16'h0001  // arm / re-arm (only while RUN.RUN=1); clears DRAIN_STAT and POP_MON
`define OP_HALT 16'h0002  // freeze the record for drain (stack: end the batch with the partial count)
`define OP_REWIND 16'h0003  // drain pointer back to DRAIN_START with DRAIN_LEN re-latched, record untouched (the app's re-drain path)
`define OP_STACK_CLEAR 16'h0004  // zero the stack accumulators and PHASE_CNT without re-arming; v3.0+ (stack, v3.1): ignored in v2.2

// ---- selectors and fields ----------------------------------------------------
// SEL_BURST_ALIAS: R pop — same as BURST (DMA/prefetch-engine friendly: the CS1 base address)
`define SEL_BURST_ALIAS 8'h00
// SEL_CLK_STAT: R — clock status
`define SEL_CLK_STAT 8'h04
`define CLK_STAT_PLLA_LOCK_MASK 16'h0001
`define CLK_STAT_PLLA_LOCK_LSB 0
`define CLK_STAT_PLLB_LOCK_MASK 16'h0002
`define CLK_STAT_PLLB_LOCK_LSB 1
`define CLK_STAT_RATIO_MASK 16'hfff0
`define CLK_STAT_RATIO_LSB 4
// SEL_DIAG_IDX: RW — index into the diagnostic window (DIAG_DATA)
`define SEL_DIAG_IDX 8'h08
`define DIAG_IDX_IDX_MASK 16'h00ff
`define DIAG_IDX_IDX_LSB 0
// SEL_DIAG_DATA: RW — the 16-bit diagnostic window selected by DIAG_IDX (layout per index in the DIAG window table)
`define SEL_DIAG_DATA 8'h0c
// SEL_BUILDID_LO: R — schema build-ID low word (from codegen; the app checks it against iface.BuildID)
`define SEL_BUILDID_LO 8'h10
// SEL_BUILDID_HI: R — schema build-ID high word
`define SEL_BUILDID_HI 8'h14
// SEL_VERSION: R — fabric self-check magic 0x00A3 (schema version 3)
`define SEL_VERSION 8'h18
// SEL_FABRIC_ID: R — 0xA2F1 = the default image
`define SEL_FABRIC_ID 8'h1c
// SEL_OPCODE: W strobe — capture opcode strobe: RESET / GO (arm or re-arm, only while RUN) / HALT / REWIND / STACK_CLEAR; any other value is ignored
`define SEL_OPCODE 8'h20
// SEL_RUN: RW — run / mode control
`define SEL_RUN 8'h24
`define RUN_MODE_MASK 16'h0003
`define RUN_MODE_LSB 0
`define RUN_MODE_AUTO 2'd0  // auto trigger
`define RUN_MODE_NORM 2'd1  // normal trigger
`define RUN_RUN_MASK 16'h0004
`define RUN_RUN_LSB 2
`define RUN_STREAM_MASK 16'h0008
`define RUN_STREAM_LSB 3
`define RUN_CHMODE_MASK 16'h0030
`define RUN_CHMODE_LSB 4
`define RUN_CHMODE_DUAL 2'd0  // both channels, word = {CH1, CH2}
`define RUN_CHMODE_CH1 2'd1  // CH1 only, word = two consecutive CH1 samples
`define RUN_CHMODE_CH2 2'd2  // CH2 only, word = two consecutive CH2 samples
`define RUN_STACK_MASK 16'h0040
`define RUN_STACK_LSB 6
`define RUN_REDUCE_MASK 16'h0080
`define RUN_REDUCE_LSB 7
// SEL_DECIM_LO: RW — decimation factor D, low word (cap_tick once per D samples; the reduce unit's block length)
`define SEL_DECIM_LO 8'h28
// SEL_DECIM_HI: RW — decimation factor, high word
`define SEL_DECIM_HI 8'h2c
// SEL_PRETRIG_LO: RW — pre-trigger samples (words), low word (<= PRETRIG_MAX; IL5 modes use multiples of ROW_COLS)
`define SEL_PRETRIG_LO 8'h30
// SEL_PRETRIG_HI: RW — pre-trigger samples, high word
`define SEL_PRETRIG_HI 8'h34
// SEL_POSTTRIG_LO: RW — post-trigger samples (words), low word
`define SEL_POSTTRIG_LO 8'h38
// SEL_POSTTRIG_HI: RW — post-trigger samples, high word
`define SEL_POSTTRIG_HI 8'h3c
// SEL_BURST: R pop — pop-on-read record word w = ROW_COLS*row + col of the drain window (row-major, column-minor, time order in every mode); a pop on an empty source returns the last word and counts POP_MON.UNDERRUN
`define SEL_BURST 8'h40
`define BURST_CH1_MASK 16'hff00
`define BURST_CH1_LSB 8
`define BURST_CH2_MASK 16'h00ff
`define BURST_CH2_LSB 0
// SEL_BURST_REMAIN: R — drain flow control
`define SEL_BURST_REMAIN 8'h44
`define BURST_REMAIN_READY_MASK 16'h8000
`define BURST_REMAIN_READY_LSB 15
`define BURST_REMAIN_REMAIN_MASK 16'h7fff
`define BURST_REMAIN_REMAIN_LSB 0
// SEL_STATUS_A: R — acquisition status (level)
`define SEL_STATUS_A 8'h48
`define STATUS_A_VALID_MASK 16'h0001
`define STATUS_A_VALID_LSB 0
`define STATUS_A_TRIG_MASK 16'h0002
`define STATUS_A_TRIG_LSB 1
`define STATUS_A_DONE_MASK 16'h0004
`define STATUS_A_DONE_LSB 2
`define STATUS_A_OVERFLOW_MASK 16'h0008
`define STATUS_A_OVERFLOW_LSB 3
`define STATUS_A_ARMED_MASK 16'h0010
`define STATUS_A_ARMED_LSB 4
// SEL_TRIGPOS_LO: R — trigger position, fractional word
`define SEL_TRIGPOS_LO 8'h4c
`define TRIGPOS_LO_FRAC_MASK 16'hffff
`define TRIGPOS_LO_FRAC_LSB 0
// SEL_TRIGPOS_HI: R — trigger position, index word
`define SEL_TRIGPOS_HI 8'h50
`define TRIGPOS_HI_IDX_MASK 16'h7fff
`define TRIGPOS_HI_IDX_LSB 0
// SEL_FILL: R — fill count
`define SEL_FILL 8'h54
`define FILL_COUNT_MASK 16'hffff
`define FILL_COUNT_LSB 0
// SEL_ACQ_CTRL: RW — acquisition control (reset 0x7c00: encode off, all pairs enabled)
`define SEL_ACQ_CTRL 8'h58
`define ACQ_CTRL_ENC_EN_MASK 16'h0001
`define ACQ_CTRL_ENC_EN_LSB 0
`define ACQ_CTRL_ENC_RATE_MASK 16'h0006
`define ACQ_CTRL_ENC_RATE_LSB 1
`define ACQ_CTRL_ENC_RATE_R12M5 2'd0  // 12.5 MHz
`define ACQ_CTRL_ENC_RATE_R50M 2'd1  // 50 MHz
`define ACQ_CTRL_ENC_RATE_R100M 2'd2  // 100 MHz, the IL5-100 tier
`define ACQ_CTRL_ENC_RATE_R200M 2'd3  // 200 MHz, the IL5-200 over-clock tier
`define ACQ_CTRL_IL_EN_MASK 16'h0008
`define ACQ_CTRL_IL_EN_LSB 3
`define ACQ_CTRL_TRIG_HYST_MASK 16'h00f0
`define ACQ_CTRL_TRIG_HYST_LSB 4
`define ACQ_CTRL_TRIG_SRC_MASK 16'h0100
`define ACQ_CTRL_TRIG_SRC_LSB 8
`define ACQ_CTRL_TRIG_SLOPE_MASK 16'h0200
`define ACQ_CTRL_TRIG_SLOPE_LSB 9
`define ACQ_CTRL_PAIR_EN_MASK 16'h7c00
`define ACQ_CTRL_PAIR_EN_LSB 10
// SEL_TRIG_LEVEL: RW — trigger level / comparator select
`define SEL_TRIG_LEVEL 8'h5c
`define TRIG_LEVEL_LEVEL_MASK 16'h00ff
`define TRIG_LEVEL_LEVEL_LSB 0
`define TRIG_LEVEL_HW_SEL_MASK 16'h0100
`define TRIG_LEVEL_HW_SEL_LSB 8
// SEL_SNOOP_SEL: R — last CS1 write, selector side
`define SEL_SNOOP_SEL 8'h60
`define SNOOP_SEL_SEL_MASK 16'h007f
`define SNOOP_SEL_SEL_LSB 0
`define SNOOP_SEL_A2_MASK 16'h0080
`define SNOOP_SEL_A2_LSB 7
`define SNOOP_SEL_B1_MASK 16'h0100
`define SNOOP_SEL_B1_LSB 8
`define SNOOP_SEL_COUNT_MASK 16'hfe00
`define SNOOP_SEL_COUNT_LSB 9
// SEL_SNOOP_DATA: R — data word of the last CS1 write
`define SEL_SNOOP_DATA 8'h64
// SEL_DIAG_CTRL: RW — diagnostic output controls (reset 0x0102)
`define SEL_DIAG_CTRL 8'h68
`define DIAG_CTRL_D2_MASK 16'h0001
`define DIAG_CTRL_D2_LSB 0
`define DIAG_CTRL_K2_EN_MASK 16'h0002
`define DIAG_CTRL_K2_EN_LSB 1
`define DIAG_CTRL_BUS_DRV_EN_MASK 16'h0004
`define DIAG_CTRL_BUS_DRV_EN_LSB 2
`define DIAG_CTRL_F2_SEL_MASK 16'h0018
`define DIAG_CTRL_F2_SEL_LSB 3
`define DIAG_CTRL_J2_SEL_MASK 16'h0060
`define DIAG_CTRL_J2_SEL_LSB 5
`define DIAG_CTRL_A11_MASK 16'h0080
`define DIAG_CTRL_A11_LSB 7
`define DIAG_CTRL_F1_MASK 16'h0100
`define DIAG_CTRL_F1_LSB 8
`define DIAG_CTRL_G1_MASK 16'h0200
`define DIAG_CTRL_G1_LSB 9
`define DIAG_CTRL_G2_MASK 16'h0400
`define DIAG_CTRL_G2_LSB 10
`define DIAG_CTRL_K1_MASK 16'h0800
`define DIAG_CTRL_K1_LSB 11
`define DIAG_CTRL_LANE_GATE_RST_MASK 16'h1000
`define DIAG_CTRL_LANE_GATE_RST_LSB 12
`define DIAG_CTRL_SNAP_CLK_MASK 16'h6000
`define DIAG_CTRL_SNAP_CLK_LSB 13
`define DIAG_CTRL_SNAP_ARM_MASK 16'h8000
`define DIAG_CTRL_SNAP_ARM_LSB 15
// SEL_SNAP_REMAIN: R — snapshot drain flow control
`define SEL_SNAP_REMAIN 8'h6c
`define SNAP_REMAIN_READY_MASK 16'h8000
`define SNAP_REMAIN_READY_LSB 15
`define SNAP_REMAIN_REMAIN_MASK 16'h7fff
`define SNAP_REMAIN_REMAIN_LSB 0
// SEL_SNAP_POP: R pop — snapshot word (pop-on-read; v3.0+: five words per delay-line row, SNAP_CTRL2)
`define SEL_SNAP_POP 8'h70
// SEL_MISC_RD: R — miscellaneous pad readback
`define SEL_MISC_RD 8'h74
`define MISC_RD_P6_MASK 16'h0001
`define MISC_RD_P6_LSB 0
`define MISC_RD_F3_MASK 16'h0002
`define MISC_RD_F3_LSB 1
`define MISC_RD_F5_MASK 16'h0004
`define MISC_RD_F5_LSB 2
`define MISC_RD_G5_MASK 16'h0008
`define MISC_RD_G5_LSB 3
`define MISC_RD_D3_MASK 16'h0010
`define MISC_RD_D3_LSB 4
`define MISC_RD_F7_MASK 16'h0020
`define MISC_RD_F7_LSB 5
`define MISC_RD_A2_MASK 16'h0040
`define MISC_RD_A2_LSB 6
`define MISC_RD_B1_MASK 16'h0080
`define MISC_RD_B1_LSB 7
`define MISC_RD_D1_MASK 16'h0100
`define MISC_RD_D1_LSB 8
`define MISC_RD_G2_MASK 16'h0200
`define MISC_RD_G2_LSB 9
`define MISC_RD_B10_MASK 16'h0400
`define MISC_RD_B10_LSB 10
`define MISC_RD_E6_MASK 16'h0800
`define MISC_RD_E6_LSB 11
// SEL_ENV_DATA: R pop — reserved (the stack readout goes through BURST); reads 0
`define SEL_ENV_DATA 8'h78
// SEL_DBG: R — fabric FSM state for bring-up (layout per fpga/default/README.md)
`define SEL_DBG 8'h7c
// SEL_IL_CTRL: RW — interleave / test-source / reduce control; v2.2 implements TSRC on the dual-E1 datapath, the other fields read 0 (v3.0+)
`define SEL_IL_CTRL 8'h25
`define IL_CTRL_IL_EN_MASK 16'h0001
`define IL_CTRL_IL_EN_LSB 0
`define IL_CTRL_CAL_EN_MASK 16'h0002
`define IL_CTRL_CAL_EN_LSB 1
`define IL_CTRL_TSRC_MASK 16'h000c
`define IL_CTRL_TSRC_LSB 2
`define IL_CTRL_TSRC_ADC 2'd0  // the converters
`define IL_CTRL_TSRC_RAMP 2'd1  // ramp, +1 per word
`define IL_CTRL_TSRC_COLTAG 2'd2  // column tag {col, row[7:0]}
`define IL_CTRL_TSRC_GLITCH 2'd3  // 0xffff in one word of every 512, else 0
`define IL_CTRL_REDUCE_MODE_MASK 16'h0070
`define IL_CTRL_REDUCE_MODE_LSB 4
`define IL_CTRL_REDUCE_MODE_RAW 3'd0  // every sample
`define IL_CTRL_REDUCE_MODE_DECIM 3'd1  // {CH1[kD], CH2[kD]}
`define IL_CTRL_REDUCE_MODE_PEAK 3'd2  // {min1,min2} then {max1,max2} per D
`define IL_CTRL_REDUCE_MODE_BOXCAR8 3'd3  // {mean1, mean2} rounded to 8 bits per D
`define IL_CTRL_REDUCE_MODE_BOXCAR16 3'd4  // {mean1 Q8.8} then {mean2 Q8.8} per D
`define IL_CTRL_IL_RATE_MASK 16'h0080
`define IL_CTRL_IL_RATE_LSB 7
`define IL_CTRL_IL_RATE_IL5_100 1'd0  // 500 MSa/s per channel
`define IL_CTRL_IL_RATE_IL5_200 1'd1  // 1 GSa/s per channel (over-clock)
`define IL_CTRL_DIV_PH_MASK 16'h1f00
`define IL_CTRL_DIV_PH_LSB 8
// SEL_DEC_RECIP: RW stub — boxcar reciprocal: mean_Q8.8 = ((sum >> DEC_PRE) * RECIP) >> 8 (06-TIERS §1.5); v3.0+: reads 0 in v2.2
`define SEL_DEC_RECIP 8'h26
`define DEC_RECIP_RECIP_MASK 16'hffff
`define DEC_RECIP_RECIP_LSB 0
// SEL_DEC_PRE: RW stub — boxcar pre-shift; v3.0+: reads 0 in v2.2
`define SEL_DEC_PRE 8'h27
`define DEC_PRE_PRE_MASK 16'h001f
`define DEC_PRE_PRE_LSB 0
// SEL_DRAIN_START: RW — drain window start; latched at DONE and at OP_REWIND
`define SEL_DRAIN_START 8'h41
`define DRAIN_START_IDX_MASK 16'h7fff
`define DRAIN_START_IDX_LSB 0
// SEL_DRAIN_LEN: RW — drain window length; latched with DRAIN_START
`define SEL_DRAIN_LEN 8'h42
`define DRAIN_LEN_LEN_MASK 16'hffff
`define DRAIN_LEN_LEN_LSB 0
// SEL_DRAIN_STAT: R — drain statistics — the pointer-delta ground truth for rung R1
`define SEL_DRAIN_STAT 8'h43
`define DRAIN_STAT_POPS_MASK 16'hffff
`define DRAIN_STAT_POPS_LSB 0
// SEL_POP_MON: R — pop monitor
`define SEL_POP_MON 8'h45
`define POP_MON_MIN_GAP_MASK 16'h00ff
`define POP_MON_MIN_GAP_LSB 0
`define POP_MON_UNDERRUN_MASK 16'hff00
`define POP_MON_UNDERRUN_LSB 8
// SEL_STACK_N: RW stub — stack batch size; v3.0+: reads 0 in v2.2
`define SEL_STACK_N 8'h46
`define STACK_N_N_MASK 16'h07ff
`define STACK_N_N_LSB 0
// SEL_STACK_CTRL: RW stub — stack geometry, readout shift, holdoff; v3.0+: reads 0 in v2.2
`define SEL_STACK_CTRL 8'h47
`define STACK_CTRL_PHASE_BINS_MASK 16'h0003
`define STACK_CTRL_PHASE_BINS_LSB 0
`define STACK_CTRL_SHIFT_MASK 16'h000c
`define STACK_CTRL_SHIFT_LSB 2
`define STACK_CTRL_HOLDOFF_MASK 16'hfff0
`define STACK_CTRL_HOLDOFF_LSB 4
// SEL_STACK_CNT: R stub — stack progress; v3.0+: reads 0 in v2.2
`define SEL_STACK_CNT 8'h49
`define STACK_CNT_RECORDS_MASK 16'h07ff
`define STACK_CNT_RECORDS_LSB 0
`define STACK_CNT_PHASE_LAST_MASK 16'h3800
`define STACK_CNT_PHASE_LAST_LSB 11
// SEL_STACK_PRE: RW stub — stack window pre-trigger; v3.0+: reads 0 in v2.2
`define SEL_STACK_PRE 8'h4a
`define STACK_PRE_ROWS_MASK 16'h01ff
`define STACK_PRE_ROWS_LSB 0
// SEL_STACK_LEN: RW stub — stack window length; v3.0+: reads 0 in v2.2
`define SEL_STACK_LEN 8'h4b
`define STACK_LEN_ROWS_MASK 16'h0fff
`define STACK_LEN_ROWS_LSB 0
// SEL_STATUS_B: R stub — tier status; v3.0+: reads 0 in v2.2
`define SEL_STATUS_B 8'h4d
`define STATUS_B_IL_ACTIVE_MASK 16'h0001
`define STATUS_B_IL_ACTIVE_LSB 0
`define STATUS_B_STACK_BUSY_MASK 16'h0002
`define STATUS_B_STACK_BUSY_LSB 1
`define STATUS_B_STACK_DONE_MASK 16'h0004
`define STATUS_B_STACK_DONE_LSB 2
`define STATUS_B_FIFO_EMPTY_MASK 16'h0008
`define STATUS_B_FIFO_EMPTY_LSB 3
`define STATUS_B_STEP_BUSY_MASK 16'h00f0
`define STATUS_B_STEP_BUSY_LSB 4
`define STATUS_B_STEP_ERR_MASK 16'h0100
`define STATUS_B_STEP_ERR_LSB 8
`define STATUS_B_CAL_SAT_MASK 16'h0200
`define STATUS_B_CAL_SAT_LSB 9
// SEL_EYE_CTRL: RW stub — eye monitor control; v3.0+: reads 0 in v2.2
`define SEL_EYE_CTRL 8'h4e
`define EYE_CTRL_CORE_MASK 16'h000f
`define EYE_CTRL_CORE_LSB 0
`define EYE_CTRL_CENTRE_MASK 16'h0ff0
`define EYE_CTRL_CENTRE_LSB 4
`define EYE_CTRL_TOL_MASK 16'h7000
`define EYE_CTRL_TOL_LSB 12
`define EYE_CTRL_EN_MASK 16'h8000
`define EYE_CTRL_EN_LSB 15
// SEL_EYE_CNT: R stub — eye monitor count; v3.0+: reads 0 in v2.2
`define SEL_EYE_CNT 8'h4f
`define EYE_CNT_COUNT_MASK 16'hffff
`define EYE_CNT_COUNT_LSB 0
// SEL_DBG2: R stub — phase-step engine debug; v3.0+: reads 0 in v2.2
`define SEL_DBG2 8'h7d
`define DBG2_STEPS_MASK 16'h00ff
`define DBG2_STEPS_LSB 0
`define DBG2_CSEL_MASK 16'h0700
`define DBG2_CSEL_LSB 8
`define DBG2_BUSY_MASK 16'h0800
`define DBG2_BUSY_LSB 11
`define DBG2_ERR_MASK 16'h1000
`define DBG2_ERR_LSB 12

// ---- DIAG window: DIAG_IDX index -> DIAG_DATA layout ----------------------------------
// DIAG_BUS_OE_LO: RW — per-ball output enable, bus balls 0..15 (J6 K5 L1 L2 L3 L4 N1 N2 P1 P2 R1 M6 N6 N3 N5 P3); effective only with DIAG_CTRL.BUS_DRV_EN
`define DIAG_BUS_OE_LO 8'h00
// DIAG_BUS_OE_HI: RW — per-ball output enable, bus balls 16..26
`define DIAG_BUS_OE_HI 8'h01
`define DIAG_BUS_OE_HI_OE_MASK 16'h07ff
`define DIAG_BUS_OE_HI_OE_LSB 0
// DIAG_BUS_DRV_LO: RW — drive level, bus balls 0..15
`define DIAG_BUS_DRV_LO 8'h02
// DIAG_BUS_DRV_HI: RW — drive level, bus balls 16..26
`define DIAG_BUS_DRV_HI 8'h03
`define DIAG_BUS_DRV_HI_DRV_MASK 16'h07ff
`define DIAG_BUS_DRV_HI_DRV_LSB 0
// DIAG_BUS_RD_LO: R — registered pad input level, bus balls 0..15
`define DIAG_BUS_RD_LO 8'h04
// DIAG_BUS_RD_HI: R — registered pad input level, bus balls 16..26
`define DIAG_BUS_RD_HI 8'h05
`define DIAG_BUS_RD_HI_RD_MASK 16'h07ff
`define DIAG_BUS_RD_HI_RD_LSB 0
// DIAG_SINGLE_CTRL: RW — the five single bidirectional balls
`define DIAG_SINGLE_CTRL 8'h06
`define DIAG_SINGLE_CTRL_OE_MASK 16'h001f
`define DIAG_SINGLE_CTRL_OE_LSB 0
`define DIAG_SINGLE_CTRL_DRV_MASK 16'h1f00
`define DIAG_SINGLE_CTRL_DRV_LSB 8
// DIAG_ADC_HOLD: RW — the proven ADC recipe (owned-fpga c8ec66d) vs bus membership of L4/T2/T7
`define DIAG_ADC_HOLD 8'h07
`define DIAG_ADC_HOLD_L4_MASK 16'h0001
`define DIAG_ADC_HOLD_L4_LSB 0
`define DIAG_ADC_HOLD_T2_MASK 16'h0002
`define DIAG_ADC_HOLD_T2_LSB 1
`define DIAG_ADC_HOLD_T7_MASK 16'h0004
`define DIAG_ADC_HOLD_T7_LSB 2
// DIAG_LANE_IDX: RW — which input LANE_TOG / LANE_LVL report
`define DIAG_LANE_IDX 8'h08
`define DIAG_LANE_IDX_IDX_MASK 16'h007f
`define DIAG_LANE_IDX_IDX_LSB 0
// DIAG_LANE_TOG: R — toggle count of LANE_IDX over the last 65536 bus-clock cycles (saturating)
`define DIAG_LANE_TOG 8'h09
// DIAG_LANE_LVL: R — level / ever-1 / ever-0 of LANE_IDX
`define DIAG_LANE_LVL 8'h0a
`define DIAG_LANE_LVL_LEVEL_MASK 16'h0001
`define DIAG_LANE_LVL_LEVEL_LSB 0
`define DIAG_LANE_LVL_EVER1_MASK 16'h0002
`define DIAG_LANE_LVL_EVER1_LSB 1
`define DIAG_LANE_LVL_EVER0_MASK 16'h0004
`define DIAG_LANE_LVL_EVER0_LSB 2
// DIAG_SNAP_MODE: RW — snapshot RAM source (v2.2, the 2048x16 snapshot; superseded by SNAP_CTRL2 in v3.0)
`define DIAG_SNAP_MODE 8'h0b
`define DIAG_SNAP_MODE_SLICE_MASK 16'h0007
`define DIAG_SNAP_MODE_SLICE_LSB 0
// DIAG_PAIR_TRIM: RW stub — per-pair encode phase trim on counters c1..c4 (E1 = c0 is the reference); a write starts the step engine on the changed counters (STATUS_B.STEP_BUSY, DBG2); replaces PHASE_SEL; v3.0+: reads 0 in v2.2
`define DIAG_PAIR_TRIM 8'h0c
`define DIAG_PAIR_TRIM_E2_MASK 16'h000f
`define DIAG_PAIR_TRIM_E2_LSB 0
`define DIAG_PAIR_TRIM_E3_MASK 16'h00f0
`define DIAG_PAIR_TRIM_E3_LSB 4
`define DIAG_PAIR_TRIM_E4_MASK 16'h0f00
`define DIAG_PAIR_TRIM_E4_LSB 8
`define DIAG_PAIR_TRIM_E5_MASK 16'hf000
`define DIAG_PAIR_TRIM_E5_LSB 12
// DIAG_IL_DLY: RW stub — per-pair row-alignment delay (reset = the hop-chain latency table; at IL5-100 the LSB selects which of the two captures of a sample is taken); v3.0+: reads 0 in v2.2
`define DIAG_IL_DLY 8'h0d
`define DIAG_IL_DLY_E1_MASK 16'h0003
`define DIAG_IL_DLY_E1_LSB 0
`define DIAG_IL_DLY_E2_MASK 16'h000c
`define DIAG_IL_DLY_E2_LSB 2
`define DIAG_IL_DLY_E3_MASK 16'h0030
`define DIAG_IL_DLY_E3_LSB 4
`define DIAG_IL_DLY_E4_MASK 16'h00c0
`define DIAG_IL_DLY_E4_LSB 6
`define DIAG_IL_DLY_E5_MASK 16'h0300
`define DIAG_IL_DLY_E5_LSB 8
// DIAG_SNAP_CTRL2: RW stub — snapshot on the delay line: SNAP_POP pops ROW_COLS words per row, SNAP_REMAIN counts words; v3.0+: reads 0 in v2.2
`define DIAG_SNAP_CTRL2 8'h0e
`define DIAG_SNAP_CTRL2_ROWS_MASK 16'h01ff
`define DIAG_SNAP_CTRL2_ROWS_LSB 0
`define DIAG_SNAP_CTRL2_SRC_MASK 16'h0600
`define DIAG_SNAP_CTRL2_SRC_LSB 9
`define DIAG_SNAP_CTRL2_SRC_LANES 2'd0  // raw 80 lanes
`define DIAG_SNAP_CTRL2_SRC_CORES 2'd1  // assembled core row
`define DIAG_SNAP_CTRL2_SRC_CAL 2'd2  // post-CAL row
`define DIAG_SNAP_CTRL2_SRC_BUS 2'd3  // bus view
`define DIAG_SNAP_CTRL2_DECIM_MASK 16'h7800
`define DIAG_SNAP_CTRL2_DECIM_LSB 11
// DIAG_LANEMAP[0..79]: R — the baked ten-core lane map (fpga/default/lanemap_seed.vh, from lanecal-2026-09-05), entry i = idx-0x10; read-only from v2.2 (a different map is a rebuild); dual mode reads CH1 from entries 0..7, CH2 from 8..15
`define DIAG_LANEMAP_BASE 8'h10
`define DIAG_LANEMAP_COUNT 80
`define DIAG_LANEMAP_LAST 8'h5f
`define DIAG_LANEMAP_LANE_MASK 16'h007f
`define DIAG_LANEMAP_LANE_LSB 0
// DIAG_CAL_OFF[0..9]: RW stub — per-core offset, core = 2*pair + ch; y = sat((x - OFF) * GAIN); v3.0+: reads 0 in v2.2
`define DIAG_CAL_OFF_BASE 8'h60
`define DIAG_CAL_OFF_COUNT 10
`define DIAG_CAL_OFF_LAST 8'h69
`define DIAG_CAL_OFF_OFF_MASK 16'h00ff
`define DIAG_CAL_OFF_OFF_LSB 0
// DIAG_CAL_GAIN[0..9]: RW stub — per-core gain, core = 2*pair + ch; v3.0+: reads 0 in v2.2
`define DIAG_CAL_GAIN_BASE 8'h6a
`define DIAG_CAL_GAIN_COUNT 10
`define DIAG_CAL_GAIN_LAST 8'h73
`define DIAG_CAL_GAIN_GAIN_MASK 16'h01ff
`define DIAG_CAL_GAIN_GAIN_LSB 0
// DIAG_PHASE_CNT[0..7]: R stub — records per phase bin in the current/last stack batch; v3.0+: reads 0 in v2.2
`define DIAG_PHASE_CNT_BASE 8'h74
`define DIAG_PHASE_CNT_COUNT 8
`define DIAG_PHASE_CNT_LAST 8'h7b
`define DIAG_PHASE_CNT_COUNT_MASK 16'hffff
`define DIAG_PHASE_CNT_COUNT_LSB 0
// DIAG_CAL_STAT: R stub — CAL stage saturation; v3.0+: reads 0 in v2.2
`define DIAG_CAL_STAT 8'h7c
`define DIAG_CAL_STAT_SAT_MASK 16'h03ff
`define DIAG_CAL_STAT_SAT_LSB 0
// DIAG_CAP_SEL[0..4]: R stub — the static capture choice per pair k = idx-0x7d (build constant, for the calibration record and the app's sanity check); v3.0+: reads 0 in v2.2
`define DIAG_CAP_SEL_BASE 8'h7d
`define DIAG_CAP_SEL_COUNT 5
`define DIAG_CAP_SEL_LAST 8'h81
`define DIAG_CAP_SEL_J_MASK 16'h0007
`define DIAG_CAP_SEL_J_LSB 0
`define DIAG_CAP_SEL_NEG_MASK 16'h0008
`define DIAG_CAP_SEL_NEG_LSB 3
`define DIAG_CAP_SEL_HOPS_MASK 16'h0030
`define DIAG_CAP_SEL_HOPS_LSB 4
// DIAG_BUSGEN_CTL: RW — 27-ball bus generator: control
`define DIAG_BUSGEN_CTL 8'h82
`define DIAG_BUSGEN_CTL_EN_MASK 16'h0001
`define DIAG_BUSGEN_CTL_EN_LSB 0
`define DIAG_BUSGEN_CTL_RATE_MASK 16'h0006
`define DIAG_BUSGEN_CTL_RATE_LSB 1
`define DIAG_BUSGEN_CTL_NPHASE_MASK 16'h0038
`define DIAG_BUSGEN_CTL_NPHASE_LSB 3
`define DIAG_BUSGEN_CTL_ONESHOT_MASK 16'h0040
`define DIAG_BUSGEN_CTL_ONESHOT_LSB 6
`define DIAG_BUSGEN_CTL_RUN_MASK 16'h0080
`define DIAG_BUSGEN_CTL_RUN_LSB 7
`define DIAG_BUSGEN_CTL_OE_PH_MASK 16'h1f00
`define DIAG_BUSGEN_CTL_OE_PH_LSB 8
`define DIAG_BUSGEN_CTL_OE_INV_MASK 16'h2000
`define DIAG_BUSGEN_CTL_OE_INV_LSB 13
// DIAG_BUSGEN_PAT[0..9]: RW — 27-ball bus generator: the word driven in each phase, two entries per phase, ball order J6 K5 L1 L2 L3 L4 N1 N2 P1 P2 R1 M6 N6 N3 N5 P3 R3 R4 R5 R6 R7 T2 T3 T4 T5 T6 T7
`define DIAG_BUSGEN_PAT_BASE 8'h83
`define DIAG_BUSGEN_PAT_COUNT 10
`define DIAG_BUSGEN_PAT_LAST 8'h8c
`define DIAG_BUSGEN_PAT_BITS_MASK 16'hffff
`define DIAG_BUSGEN_PAT_BITS_LSB 0
// DIAG_BUSGEN_AUX: RW — 27-ball bus generator: what the four clock-shaped balls carry while EN
`define DIAG_BUSGEN_AUX 8'h8d
`define DIAG_BUSGEN_AUX_K2_MASK 16'h0007
`define DIAG_BUSGEN_AUX_K2_LSB 0
`define DIAG_BUSGEN_AUX_D1_MASK 16'h0038
`define DIAG_BUSGEN_AUX_D1_LSB 3
`define DIAG_BUSGEN_AUX_D2_MASK 16'h01c0
`define DIAG_BUSGEN_AUX_D2_LSB 6
`define DIAG_BUSGEN_AUX_G2_MASK 16'h0e00
`define DIAG_BUSGEN_AUX_G2_LSB 9
`define DIAG_BUSGEN_AUX_K1_MASK 16'h7000
`define DIAG_BUSGEN_AUX_K1_LSB 12
// DIAG_BUSCAP_CTL: RW — 27-ball bus capture: control and status
`define DIAG_BUSCAP_CTL 8'h8e
`define DIAG_BUSCAP_CTL_EN_MASK 16'h0001
`define DIAG_BUSCAP_CTL_EN_LSB 0
`define DIAG_BUSCAP_CTL_TRIG_MASK 16'h0002
`define DIAG_BUSCAP_CTL_TRIG_LSB 1
`define DIAG_BUSCAP_CTL_TRIGGERED_MASK 16'h0004
`define DIAG_BUSCAP_CTL_TRIGGERED_LSB 2
`define DIAG_BUSCAP_CTL_WAITING_MASK 16'h0008
`define DIAG_BUSCAP_CTL_WAITING_LSB 3
`define DIAG_BUSCAP_CTL_CONFIRM_MASK 16'h0030
`define DIAG_BUSCAP_CTL_CONFIRM_LSB 4
// DIAG_BUSGEN_OE_LO: RW — 27-ball bus generator: per-ball drive mask, low half — ANDed with BUSGEN_CTL.OE_PH so a subset of the group can be driven while the rest is listened to (BUSCAP's departure trigger only watches the balls this mask leaves alone)
`define DIAG_BUSGEN_OE_LO 8'h8f
`define DIAG_BUSGEN_OE_LO_MASK_MASK 16'hffff
`define DIAG_BUSGEN_OE_LO_MASK_LSB 0
// DIAG_BUSGEN_OE_HI: RW — 27-ball bus generator: per-ball drive mask, high half
`define DIAG_BUSGEN_OE_HI 8'h90
`define DIAG_BUSGEN_OE_HI_MASK_MASK 16'h07ff
`define DIAG_BUSGEN_OE_HI_MASK_LSB 0
// DIAG_SRCLK_CTRL: RW — counted-edge crank: sources, control ball, snapshot coupling and the hardware abort
`define DIAG_SRCLK_CTRL 8'h91
`define DIAG_SRCLK_CTRL_F2_SRC_MASK 16'h0003
`define DIAG_SRCLK_CTRL_F2_SRC_LSB 0
`define DIAG_SRCLK_CTRL_F2_SRC_LEGACY 2'd0  // the DIAG_CTRL.F2_SEL level (reset; bit-for-bit the pre-crank image)
`define DIAG_SRCLK_CTRL_F2_SRC_ZERO 2'd1  // static 0 regardless of DIAG_CTRL
`define DIAG_SRCLK_CTRL_F2_SRC_CRANK 2'd2  // the counted-edge emitter; parked static 0 between bursts
`define DIAG_SRCLK_CTRL_J2_SRC_MASK 16'h000c
`define DIAG_SRCLK_CTRL_J2_SRC_LSB 2
`define DIAG_SRCLK_CTRL_J2_SRC_LEGACY 2'd0  // the DIAG_CTRL.J2_SEL level (reset)
`define DIAG_SRCLK_CTRL_J2_SRC_ZERO 2'd1  // static 0
`define DIAG_SRCLK_CTRL_J2_SRC_CRANK 2'd2  // the counted-edge emitter
`define DIAG_SRCLK_CTRL_CTRL_G2_MASK 16'h0010
`define DIAG_SRCLK_CTRL_CTRL_G2_LSB 4
`define DIAG_SRCLK_CTRL_SNAP_ON_ARM_MASK 16'h0020
`define DIAG_SRCLK_CTRL_SNAP_ON_ARM_LSB 5
`define DIAG_SRCLK_CTRL_D1_SRC_MASK 16'h0300
`define DIAG_SRCLK_CTRL_D1_SRC_LSB 8
`define DIAG_SRCLK_CTRL_D1_SRC_LEGACY 2'd0  // the BUSGEN_AUX.D1 level (reset; D1 undriven, its acquisition rest posture)
`define DIAG_SRCLK_CTRL_D1_SRC_ZERO 2'd1  // static 0 regardless of BUSGEN_AUX
`define DIAG_SRCLK_CTRL_D1_SRC_CRANK 2'd2  // the counted-edge emitter, SDR on clk100. D1 is already bidir with a fabric OE, so this costs no pad direction change and no DDIO cell — and it is the only ball on this device with BOTH a pad readback (SRCLK_ARR_D1) and a far-end witness (SRCLK_ARR_P6, since [BENCH] P6 = (NOT D1) OR D2). Refused unless DIV >= 2, which keeps the SDR shape bit-identical to the DDIO one and the narrowest phase 2 samples wide
`define DIAG_SRCLK_CTRL_GUARD_MASK 16'h00c0
`define DIAG_SRCLK_CTRL_GUARD_LSB 6
`define DIAG_SRCLK_CTRL_GUARD_OFF 2'd0  // no hardware abort; only permitted with NEDGE = 1
`define DIAG_SRCLK_CTRL_GUARD_LANES 2'd1  // the 80 ADC lanes (reset)
`define DIAG_SRCLK_CTRL_GUARD_ALL 2'd2  // the 80 lanes plus the 27 bus balls, 5 singles and P6
// DIAG_SRCLK_N: RW — counted-edge crank: how many edges, and how fast
`define DIAG_SRCLK_N 8'h92
`define DIAG_SRCLK_N_NEDGE_MASK 16'h03ff
`define DIAG_SRCLK_N_NEDGE_LSB 0
`define DIAG_SRCLK_N_DIV_MASK 16'h7c00
`define DIAG_SRCLK_N_DIV_LSB 10
// DIAG_SRCLK_DLY: RW — counted-edge crank: arm-to-first-edge delay, so one snapshot holds PRE and POST
`define DIAG_SRCLK_DLY 8'h93
`define DIAG_SRCLK_DLY_DLY_MASK 16'h03ff
`define DIAG_SRCLK_DLY_DLY_LSB 0
// DIAG_SRCLK_ARM: RW — counted-edge crank: keyed arm / stop / clear strobe (no stored state)
`define DIAG_SRCLK_ARM 8'h94
`define DIAG_SRCLK_ARM_KEY_MASK 16'h00ff
`define DIAG_SRCLK_ARM_KEY_LSB 0
`define DIAG_SRCLK_ARM_ARM_MASK 16'h0100
`define DIAG_SRCLK_ARM_ARM_LSB 8
`define DIAG_SRCLK_ARM_STOP_MASK 16'h0200
`define DIAG_SRCLK_ARM_STOP_LSB 9
`define DIAG_SRCLK_ARM_CLR_MASK 16'h0400
`define DIAG_SRCLK_ARM_CLR_LSB 10
// DIAG_SRCLK_STAT: R — counted-edge crank: status (read while BUSY = 0; the crossing is per-bit)
`define DIAG_SRCLK_STAT 8'h95
`define DIAG_SRCLK_STAT_REMAIN_MASK 16'h03ff
`define DIAG_SRCLK_STAT_REMAIN_LSB 0
`define DIAG_SRCLK_STAT_BUSY_MASK 16'h0400
`define DIAG_SRCLK_STAT_BUSY_LSB 10
`define DIAG_SRCLK_STAT_ABORTED_MASK 16'h0800
`define DIAG_SRCLK_STAT_ABORTED_LSB 11
`define DIAG_SRCLK_STAT_REFUSED_MASK 16'h1000
`define DIAG_SRCLK_STAT_REFUSED_LSB 12
`define DIAG_SRCLK_STAT_REFUSE_MASK 16'he000
`define DIAG_SRCLK_STAT_REFUSE_LSB 13
// DIAG_SRCLK_CNT_F2: R — counted-edge crank: edges emitted on F2 since arm
`define DIAG_SRCLK_CNT_F2 8'h96
`define DIAG_SRCLK_CNT_F2_EMITTED_MASK 16'hffff
`define DIAG_SRCLK_CNT_F2_EMITTED_LSB 0
// DIAG_SRCLK_CNT_J2: R — counted-edge crank: edges emitted on J2 since arm
`define DIAG_SRCLK_CNT_J2 8'h97
`define DIAG_SRCLK_CNT_J2_EMITTED_MASK 16'hffff
`define DIAG_SRCLK_CNT_J2_EMITTED_LSB 0
// DIAG_SRCLK_LIFE: R — counted-edge crank: the whole-configuration edge ceiling
`define DIAG_SRCLK_LIFE 8'h98
`define DIAG_SRCLK_LIFE_EDGES_MASK 16'hffff
`define DIAG_SRCLK_LIFE_EDGES_LSB 0
// DIAG_SRCLK_DEP: R — counted-edge crank: the departure report, latched by the hardware abort
`define DIAG_SRCLK_DEP 8'h99
`define DIAG_SRCLK_DEP_GRP_MASK 16'h003f
`define DIAG_SRCLK_DEP_GRP_LSB 0
`define DIAG_SRCLK_DEP_ABORT_EDGE_MASK 16'hffc0
`define DIAG_SRCLK_DEP_ABORT_EDGE_LSB 6
// DIAG_SRCLK_CNT_D1: R — counted-edge crank: edges emitted on D1 since arm
`define DIAG_SRCLK_CNT_D1 8'h9a
`define DIAG_SRCLK_CNT_D1_EMITTED_MASK 16'hffff
`define DIAG_SRCLK_CNT_D1_EMITTED_LSB 0
// DIAG_SRCLK_ARR_D1: R — counted-edge crank: edges present on the D1 pad since arm
`define DIAG_SRCLK_ARR_D1 8'h9b
`define DIAG_SRCLK_ARR_D1_ARRIVED_MASK 16'hffff
`define DIAG_SRCLK_ARR_D1_ARRIVED_LSB 0
// DIAG_SRCLK_ARR_P6: R — counted-edge crank: MAX V responses to D1 seen at P6 since arm
`define DIAG_SRCLK_ARR_P6 8'h9c
`define DIAG_SRCLK_ARR_P6_ARRIVED_MASK 16'hffff
`define DIAG_SRCLK_ARR_P6_ARRIVED_LSB 0
// DIAG_SRCLK_W: RW — counted-edge crank: pulse width, held independent of the period
`define DIAG_SRCLK_W 8'h9d
`define DIAG_SRCLK_W_HIGH_MASK 16'h03ff
`define DIAG_SRCLK_W_HIGH_LSB 0
// DIAG_BUSGEN_PRE: RW — 27-ball bus generator: phase-advance prescaler, so the group can be driven slowly
`define DIAG_BUSGEN_PRE 8'h9e
`define DIAG_BUSGEN_PRE_PRE_MASK 16'hffff
`define DIAG_BUSGEN_PRE_PRE_LSB 0
`define DIAG_RESERVED_BASE 8'h9f  // indices from here up read 0 and ignore writes

`endif
