// Command ifacegen validates the default-image schema (codegen/ifacedef) and
// writes the four generated artifacts, relative to the repository root:
//
//	fpga/default/regs.vh               Verilog `define header
//	fpga/default/regmux.vh             Verilog selector-decode include
//	app/internal/iface/iface.go        Go bindings
//	fpga/default/docs/REGISTER-MAP.md  register-map reference
//
// The build-ID folds in a digest of the RTL sources (-rtl globs, relative to
// -root) so an RTL-only change moves the ID and the app reloads the fabric; an
// RTL edit therefore requires `make generate` (the drift gate enforces it).
//
//	go run ./cmd/ifacegen -root ..          regenerate in place
//	go run ./cmd/ifacegen -root .. -check   drift gate: render into a temp dir, exit 1 if any
//	                                        checked-in artifact differs (nothing is written to the tree)
package main

import (
	"bytes"
	"flag"
	"fmt"
	"hash/fnv"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"open-sds/codegen/emit"
	"open-sds/codegen/ifacedef"
	"open-sds/codegen/schema"
)

// Target is one generated artifact: its path relative to the repo root and its content.
type Target struct {
	Path    string
	Content string
}

// Targets renders every artifact in a fixed order. The generator, the -check
// gate and the drift test all go through here, so an artifact cannot be added
// to one and forgotten by the others.
func Targets(i schema.Interface) ([]Target, error) {
	regs, err := emit.Regs(i)
	if err != nil {
		return nil, err
	}
	regmux, err := emit.Regmux(i)
	if err != nil {
		return nil, err
	}
	bind, err := emit.GoBindings(i)
	if err != nil {
		return nil, err
	}
	doc, err := emit.Doc(i)
	if err != nil {
		return nil, err
	}
	return []Target{
		{"fpga/default/regs.vh", regs},
		{"fpga/default/regmux.vh", regmux},
		{"app/internal/iface/iface.go", bind},
		{"fpga/default/docs/REGISTER-MAP.md", doc},
	}, nil
}

// Drift regenerates into tmpDir and compares each artifact against its
// checked-in copy under root. It returns the relative paths that differ (or are
// missing) and never writes into root.
func Drift(i schema.Interface, root, tmpDir string) ([]string, error) {
	ts, err := Targets(i)
	if err != nil {
		return nil, err
	}
	var stale []string
	for _, t := range ts {
		tmp := filepath.Join(tmpDir, t.Path)
		if err := os.MkdirAll(filepath.Dir(tmp), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(tmp, []byte(t.Content), 0o644); err != nil {
			return nil, err
		}
		have, err := os.ReadFile(filepath.Join(root, t.Path))
		if err != nil || !bytes.Equal(have, []byte(t.Content)) {
			stale = append(stale, t.Path)
		}
	}
	return stale, nil
}

// DefaultRTL are the source globs (relative to the repo root) the build-ID
// digests. The generated includes (regs.vh, regmux.vh) are excluded: they carry
// the ID itself. lanemap_seed.vh is NOT generated by ifacegen (tools/portspec/
// lanemapgen.py bakes it from the lanecal report) and diag.v consumes it, so a
// re-baked map must move the build-ID like any other RTL edit.
const DefaultRTL = "fpga/common/*.v,fpga/default/*.v,fpga/default/*.sdc,fpga/default/*.qsf,fpga/default/lanemap_seed.vh"

// SourceDigest hashes the files matched by the comma-separated globs (path and
// content, in sorted path order) to the 32-bit digest the schema folds into the
// build-ID. It returns the matched paths for the log line.
func SourceDigest(root, globs string) (uint32, []string, error) {
	var files []string
	for _, g := range strings.Split(globs, ",") {
		g = strings.TrimSpace(g)
		if g == "" {
			continue
		}
		m, err := filepath.Glob(filepath.Join(root, g))
		if err != nil {
			return 0, nil, err
		}
		files = append(files, m...)
	}
	sort.Strings(files)
	h := fnv.New64a()
	var rel []string
	for _, f := range files {
		r, err := filepath.Rel(root, f)
		if err != nil {
			return 0, nil, err
		}
		data, err := os.ReadFile(f)
		if err != nil {
			return 0, nil, err
		}
		fmt.Fprintf(h, "%s\n%d\n", filepath.ToSlash(r), len(data))
		h.Write(data)
		rel = append(rel, filepath.ToSlash(r))
	}
	s := h.Sum64()
	return uint32(s>>32) ^ uint32(s), rel, nil
}

func main() {
	root := flag.String("root", "..", "repository root the artifact paths are relative to")
	check := flag.Bool("check", false, "drift gate: regenerate into a temp dir and fail if a checked-in artifact differs")
	rtl := flag.String("rtl", DefaultRTL, "comma-separated RTL source globs (relative to -root) digested into the build-ID; empty = schema-only")
	flag.Parse()

	i := ifacedef.Default()
	if *rtl != "" {
		d, files, err := SourceDigest(*root, *rtl)
		if err != nil {
			fmt.Fprintln(os.Stderr, "ifacegen:", err)
			os.Exit(2)
		}
		if len(files) == 0 {
			fmt.Fprintf(os.Stderr, "ifacegen: -rtl %q matched no files under %s\n", *rtl, *root)
			os.Exit(2)
		}
		i.SourceDigest = d
		fmt.Printf("ifacegen: RTL digest 0x%08x over %d files\n", d, len(files))
	}
	if errs := i.Validate(); len(errs) > 0 {
		fmt.Fprintf(os.Stderr, "ifacegen: schema %s v%d is invalid:\n", i.Name, i.Version)
		for _, e := range errs {
			fmt.Fprintf(os.Stderr, "  %s\n", e)
		}
		os.Exit(2)
	}
	if *check {
		tmp, err := os.MkdirTemp("", "ifacegen-drift-")
		if err != nil {
			fmt.Fprintln(os.Stderr, "ifacegen:", err)
			os.Exit(2)
		}
		defer os.RemoveAll(tmp)
		stale, err := Drift(i, *root, tmp)
		if err != nil {
			fmt.Fprintln(os.Stderr, "ifacegen:", err)
			os.Exit(2)
		}
		if len(stale) > 0 {
			fmt.Fprintf(os.Stderr, "ifacegen: DRIFT — %d generated artifact(s) differ from the schema (build-ID 0x%08x); run `make generate` in codegen/:\n", len(stale), i.BuildID())
			for _, s := range stale {
				fmt.Fprintf(os.Stderr, "  %s\n", s)
			}
			os.Exit(1)
		}
		fmt.Printf("ifacegen: no drift (%s v%d, build-ID 0x%08x)\n", i.Name, i.Version, i.BuildID())
		return
	}
	ts, err := Targets(i)
	if err != nil {
		fmt.Fprintln(os.Stderr, "ifacegen:", err)
		os.Exit(2)
	}
	for _, t := range ts {
		path := filepath.Join(*root, t.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintln(os.Stderr, "ifacegen:", err)
			os.Exit(2)
		}
		if err := os.WriteFile(path, []byte(t.Content), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "ifacegen:", err)
			os.Exit(2)
		}
		fmt.Printf("ifacegen: wrote %s (%d bytes)\n", path, len(t.Content))
	}
	fmt.Printf("ifacegen: %s v%d build-ID 0x%08x\n", i.Name, i.Version, i.BuildID())
}
