// Code generated by codegen/cmd/ifacegen; DO NOT EDIT.
// GENERATED by codegen/cmd/ifacegen — DO NOT EDIT. Source: codegen/ifacedef.

// Package iface is the app's view of the owned FPGA<->app interface (DESIGN §3.4):
// selectors, plane/access/semantics constants, the register + auto-inc tables,
// typed field accessors, channel record codecs, the build-ID handshake, and the
// schema-derived write guard. The acquisition engine drives the fabric through
// these — never through hand-packed masks or magic ranges. Regenerated from
// codegen/ifacedef by ifacegen; edit the schema, not this file.
package iface

import "fmt"

// BuildID fingerprints the schema; the app checks it vs BUILDID_LO/HI at bring-up
// and refuses to drive a fabric whose build-ID differs.
const BuildID uint32 = 0x4a9ccfa4

// Version is the schema version string.
const Version = "1"

// ExpectVERSION is the value a correct fabric returns for the
// VERSION identity register — the cheap addressing self-check the
// app performs (both iface.Verify and the mmap fast path use this one const, so no
// consumer hand-maintains the magic).
const ExpectVERSION uint16 = 0x0052

// Plane is a GPMC chip-select register window.
type Plane uint8

const (
	CS1 Plane = 1
	CS3 Plane = 3
)

// Access is the read/write capability of a register (matches schema.Access).
type Access uint8

const (
	AccR  Access = 1
	AccW  Access = 2
	AccRW Access = 3
)

func (a Access) CanRead() bool  { return a&AccR != 0 }
func (a Access) CanWrite() bool { return a&AccW != 0 }

// Sem is the behavioral access-semantics bitset (matches schema.Sem).
type Sem uint16

const (
	SemNormal        Sem = 1
	SemStrobe        Sem = 2
	SemAutoIncPort   Sem = 4
	SemReadAfterHalt Sem = 8
	SemLevelStatus   Sem = 16
	SemWaitGuarded   Sem = 32
)

// Selectors — pass UNSHIFTED; the driver applies the <<1 byte-address shift.
const (
	SelBUILDID_LO   uint16 = 0x10
	SelBUILDID_HI   uint16 = 0x11
	SelVERSION      uint16 = 0x12
	SelOPCODE       uint16 = 0x20
	SelRUN          uint16 = 0x21
	SelDECIM_LO     uint16 = 0x22
	SelDECIM_HI     uint16 = 0x23
	SelPRETRIG_LO   uint16 = 0x24
	SelPRETRIG_HI   uint16 = 0x25
	SelPOSTTRIG_LO  uint16 = 0x26
	SelPOSTTRIG_HI  uint16 = 0x27
	SelBURST        uint16 = 0x30
	SelBURST_REMAIN uint16 = 0x3e
	SelSTATUS_A     uint16 = 0x41
	SelTRIGPOS_LO   uint16 = 0x42
	SelTRIGPOS_HI   uint16 = 0x43
	SelFILL         uint16 = 0x44
	SelXFORM_CTRL   uint16 = 0x50
	SelENV_COLS     uint16 = 0x51
	SelENV_DATA     uint16 = 0x60
	SelENV_COUNT    uint16 = 0x61
	SelENV_RESET    uint16 = 0x62
	SelCONF_DONE    uint16 = 0x07
	SelLED_LO       uint16 = 0x09
	SelLED_HI       uint16 = 0x0a
	SelLED_STROBE   uint16 = 0x0b
	SelOFF_C1_LO    uint16 = 0x10
	SelOFF_C2_LO    uint16 = 0x11
	SelOFF_C1_HI    uint16 = 0x30
	SelOFF_C2_HI    uint16 = 0x31
	SelLVL_A_LO     uint16 = 0x14
	SelLVL_B_LO     uint16 = 0x15
	SelLVL_A_HI     uint16 = 0x34
	SelLVL_B_HI     uint16 = 0x35
)

// Opcodes — strobe payload values. The app writes these to the named strobe
// register; the RTL decodes the same macro literal (folded into BuildID), so the
// command encoding cannot silently drift between app and fabric.
const (
	OP_RESET uint16 = 0x0000 // OPCODE: idle the capture FSM
	OP_GO    uint16 = 0x0001 // OPCODE: arm / fast re-arm (honored only while RUN)
	OP_HALT  uint16 = 0x0002 // OPCODE: freeze the record
)

// Reg is one register's metadata (for runtime assertion / tooling).
type Reg struct {
	Name   string
	Sel    uint16
	Plane  Plane
	Access Access
	Sem    Sem
}

// Registers is the full metadata table, in declaration order.
var Registers = []Reg{
	{"BUILDID_LO", 0x10, CS1, AccR, 1},
	{"BUILDID_HI", 0x11, CS1, AccR, 1},
	{"VERSION", 0x12, CS1, AccR, 1},
	{"OPCODE", 0x20, CS1, AccW, 2},
	{"RUN", 0x21, CS1, AccRW, 1},
	{"DECIM_LO", 0x22, CS1, AccRW, 1},
	{"DECIM_HI", 0x23, CS1, AccRW, 1},
	{"PRETRIG_LO", 0x24, CS1, AccRW, 1},
	{"PRETRIG_HI", 0x25, CS1, AccRW, 1},
	{"POSTTRIG_LO", 0x26, CS1, AccRW, 1},
	{"POSTTRIG_HI", 0x27, CS1, AccRW, 1},
	{"BURST", 0x30, CS1, AccR, 12},
	{"BURST_REMAIN", 0x3e, CS1, AccR, 24},
	{"STATUS_A", 0x41, CS1, AccR, 16},
	{"TRIGPOS_LO", 0x42, CS1, AccR, 24},
	{"TRIGPOS_HI", 0x43, CS1, AccR, 24},
	{"FILL", 0x44, CS1, AccR, 16},
	{"XFORM_CTRL", 0x50, CS1, AccRW, 1},
	{"ENV_COLS", 0x51, CS1, AccRW, 1},
	{"ENV_DATA", 0x60, CS1, AccR, 12},
	{"ENV_COUNT", 0x61, CS1, AccR, 16},
	{"ENV_RESET", 0x62, CS1, AccW, 2},
	{"CONF_DONE", 0x07, CS3, AccR, 16},
	{"LED_LO", 0x09, CS3, AccW, 1},
	{"LED_HI", 0x0a, CS3, AccW, 1},
	{"LED_STROBE", 0x0b, CS3, AccW, 2},
	{"OFF_C1_LO", 0x10, CS3, AccW, 1},
	{"OFF_C2_LO", 0x11, CS3, AccW, 1},
	{"OFF_C1_HI", 0x30, CS3, AccW, 1},
	{"OFF_C2_HI", 0x31, CS3, AccW, 1},
	{"LVL_A_LO", 0x14, CS3, AccW, 1},
	{"LVL_B_LO", 0x15, CS3, AccW, 1},
	{"LVL_A_HI", 0x34, CS3, AccW, 2},
	{"LVL_B_HI", 0x35, CS3, AccW, 2},
}

// AutoIncPorts lists the auto-increment read ports: reading one advances an
// internal pointer (pops one word). PLANE-QUALIFIED — match on {Plane,Sel},
// never selector alone (a selector can repeat across planes). The bus layer must
// treat such a read as a mutation: never dedup, speculate, or CSE it.
var AutoIncPorts = []Reg{
	{"BURST", 0x30, CS1, AccR, 12},
	{"ENV_DATA", 0x60, CS1, AccR, 12},
}

// Field masks and shifts.
const (
	Mask_RUN_MODE             uint16 = 0x0003
	Shift_RUN_MODE            uint   = 0
	Mask_RUN_RUN              uint16 = 0x0004
	Shift_RUN_RUN             uint   = 2
	Mask_BURST_REMAIN_READY   uint16 = 0x8000
	Shift_BURST_REMAIN_READY  uint   = 15
	Mask_BURST_REMAIN_REMAIN  uint16 = 0x7fff
	Shift_BURST_REMAIN_REMAIN uint   = 0
	Mask_STATUS_A_VALID       uint16 = 0x0001
	Shift_STATUS_A_VALID      uint   = 0
	Mask_STATUS_A_TRIG        uint16 = 0x0002
	Shift_STATUS_A_TRIG       uint   = 1
	Mask_STATUS_A_DONE        uint16 = 0x0004
	Shift_STATUS_A_DONE       uint   = 2
	Mask_TRIGPOS_LO_FRAC      uint16 = 0xffff
	Shift_TRIGPOS_LO_FRAC     uint   = 0
	Mask_TRIGPOS_HI_IDX       uint16 = 0x7fff
	Shift_TRIGPOS_HI_IDX      uint   = 0
	Mask_FILL_COUNT           uint16 = 0x07ff
	Shift_FILL_COUNT          uint   = 0
	Mask_XFORM_CTRL_BYPASS0   uint16 = 0x0001
	Shift_XFORM_CTRL_BYPASS0  uint   = 0
	Mask_XFORM_CTRL_BYPASS1   uint16 = 0x0002
	Shift_XFORM_CTRL_BYPASS1  uint   = 1
	Mask_ENV_COUNT_COUNT      uint16 = 0x7fff
	Shift_ENV_COUNT_COUNT     uint   = 0
	Mask_ENV_COUNT_OVERFLOW   uint16 = 0x8000
	Shift_ENV_COUNT_OVERFLOW  uint   = 15
	Mask_CONF_DONE_DONE       uint16 = 0x0080
	Shift_CONF_DONE_DONE      uint   = 7
)

// ---- typed field accessors (generated from Fields) -----------------------
// Getters take a read word; builders return a word with a single field set (OR
// them together to compose a write, e.g. RunWithMode(m) | RunWithRun(true)).

// RunMode extracts RUN.MODE from a read word.
func RunMode(w uint16) uint8 {
	return uint8((w & Mask_RUN_MODE) >> Shift_RUN_MODE)
}

// RunWithMode returns a word with RUN.MODE set to v.
func RunWithMode(v uint8) uint16 {
	return (uint16(v) << Shift_RUN_MODE) & Mask_RUN_MODE
}

// RunRun extracts RUN.RUN from a read word.
func RunRun(w uint16) bool {
	return w&Mask_RUN_RUN != 0
}

// RunWithRun returns a word with RUN.RUN set to v.
func RunWithRun(v bool) uint16 {
	if v {
		return Mask_RUN_RUN
	}
	return 0
}

// BurstRemainReady extracts BURST_REMAIN.READY from a read word.
func BurstRemainReady(w uint16) bool {
	return w&Mask_BURST_REMAIN_READY != 0
}

// BurstRemainRemain extracts BURST_REMAIN.REMAIN from a read word.
func BurstRemainRemain(w uint16) uint16 {
	return uint16((w & Mask_BURST_REMAIN_REMAIN) >> Shift_BURST_REMAIN_REMAIN)
}

// StatusAValid extracts STATUS_A.VALID from a read word.
func StatusAValid(w uint16) bool {
	return w&Mask_STATUS_A_VALID != 0
}

// StatusATrig extracts STATUS_A.TRIG from a read word.
func StatusATrig(w uint16) bool {
	return w&Mask_STATUS_A_TRIG != 0
}

// StatusADone extracts STATUS_A.DONE from a read word.
func StatusADone(w uint16) bool {
	return w&Mask_STATUS_A_DONE != 0
}

// TrigposLoFrac extracts TRIGPOS_LO.FRAC from a read word.
func TrigposLoFrac(w uint16) uint16 {
	return uint16((w & Mask_TRIGPOS_LO_FRAC) >> Shift_TRIGPOS_LO_FRAC)
}

// TrigposHiIdx extracts TRIGPOS_HI.IDX from a read word.
func TrigposHiIdx(w uint16) uint16 {
	return uint16((w & Mask_TRIGPOS_HI_IDX) >> Shift_TRIGPOS_HI_IDX)
}

// FillCount extracts FILL.COUNT from a read word.
func FillCount(w uint16) uint16 {
	return uint16((w & Mask_FILL_COUNT) >> Shift_FILL_COUNT)
}

// XformCtrlBypass0 extracts XFORM_CTRL.BYPASS0 from a read word.
func XformCtrlBypass0(w uint16) bool {
	return w&Mask_XFORM_CTRL_BYPASS0 != 0
}

// XformCtrlWithBypass0 returns a word with XFORM_CTRL.BYPASS0 set to v.
func XformCtrlWithBypass0(v bool) uint16 {
	if v {
		return Mask_XFORM_CTRL_BYPASS0
	}
	return 0
}

// XformCtrlBypass1 extracts XFORM_CTRL.BYPASS1 from a read word.
func XformCtrlBypass1(w uint16) bool {
	return w&Mask_XFORM_CTRL_BYPASS1 != 0
}

// XformCtrlWithBypass1 returns a word with XFORM_CTRL.BYPASS1 set to v.
func XformCtrlWithBypass1(v bool) uint16 {
	if v {
		return Mask_XFORM_CTRL_BYPASS1
	}
	return 0
}

// EnvCountCount extracts ENV_COUNT.COUNT from a read word.
func EnvCountCount(w uint16) uint16 {
	return uint16((w & Mask_ENV_COUNT_COUNT) >> Shift_ENV_COUNT_COUNT)
}

// EnvCountOverflow extracts ENV_COUNT.OVERFLOW from a read word.
func EnvCountOverflow(w uint16) bool {
	return w&Mask_ENV_COUNT_OVERFLOW != 0
}

// ConfDoneDone extracts CONF_DONE.DONE from a read word.
func ConfDoneDone(w uint16) bool {
	return w&Mask_CONF_DONE_DONE != 0
}

// ---- channel record codecs -----------------------------------------------
// Records pack their fields LSB-first, in declaration order, across a []uint16.
// recGet/recSet are the shared little-endian bit-slice helpers.

func recGet(w []uint16, off, width uint) uint64 {
	var v uint64
	for i := uint(0); i < width; i++ {
		bit := off + i
		if int(bit/16) < len(w) && w[bit/16]&(1<<(bit%16)) != 0 {
			v |= 1 << i
		}
	}
	return v
}

func recSet(w []uint16, off, width uint, v uint64) {
	for i := uint(0); i < width; i++ {
		if v&(1<<i) != 0 {
			bit := off + i
			if int(bit/16) < len(w) {
				w[bit/16] |= 1 << (bit % 16)
			}
		}
	}
}

// EnvelopeRecord is the decoded envelope record (40 bits, 3 words). display-ready min/max per time-column (results, not raw); folded on the live stream
type EnvelopeRecord struct {
	Col      uint16 // [15:0] display column index
	Min      uint8  // [23:16] column min sample
	Max      uint8  // [31:24] column max sample
	Ch       uint8  // [35:32] channel
	Rsvd     uint8  // [38:36]
	Overflow bool   // [39:39] columns dropped since last read
}

// Unpack decodes one envelope record from w (LSB-first; needs >= 3 words).
func (r *EnvelopeRecord) Unpack(w []uint16) {
	r.Col = uint16(recGet(w, 0, 16))
	r.Min = uint8(recGet(w, 16, 8))
	r.Max = uint8(recGet(w, 24, 8))
	r.Ch = uint8(recGet(w, 32, 4))
	r.Rsvd = uint8(recGet(w, 36, 3))
	r.Overflow = recGet(w, 39, 1) != 0
}

// Pack encodes one envelope record into 3 words (LSB-first).
func (r EnvelopeRecord) Pack() []uint16 {
	w := make([]uint16, 3)
	recSet(w, 0, 16, uint64(r.Col))
	recSet(w, 16, 8, uint64(r.Min))
	recSet(w, 24, 8, uint64(r.Max))
	recSet(w, 32, 4, uint64(r.Ch))
	recSet(w, 36, 3, uint64(r.Rsvd))
	if r.Overflow {
		recSet(w, 39, 1, 1)
	}
	return w
}

// MeasureRecord is the decoded measure record (48 bits, 3 words). RESERVED (v1): HW measurement results (Vpp/RMS/freq/period/rise/fall/duty)
type MeasureRecord struct {
	Kind     uint8  // [7:0] measurement kind
	Ch       uint8  // [11:8] channel
	Rsvd     uint8  // [14:12]
	Overflow bool   // [15:15] results dropped since last read
	Value    uint32 // [47:16] measurement value (fixed-point)
}

// Unpack decodes one measure record from w (LSB-first; needs >= 3 words).
func (r *MeasureRecord) Unpack(w []uint16) {
	r.Kind = uint8(recGet(w, 0, 8))
	r.Ch = uint8(recGet(w, 8, 4))
	r.Rsvd = uint8(recGet(w, 12, 3))
	r.Overflow = recGet(w, 15, 1) != 0
	r.Value = uint32(recGet(w, 16, 32))
}

// Pack encodes one measure record into 3 words (LSB-first).
func (r MeasureRecord) Pack() []uint16 {
	w := make([]uint16, 3)
	recSet(w, 0, 8, uint64(r.Kind))
	recSet(w, 8, 4, uint64(r.Ch))
	recSet(w, 12, 3, uint64(r.Rsvd))
	if r.Overflow {
		recSet(w, 15, 1, 1)
	}
	recSet(w, 16, 32, uint64(r.Value))
	return w
}

// TrigEventRecord is the decoded trig_event record (48 bits, 3 words). RESERVED (v1): trigger-event ring — idx + kind per fired trigger
type TrigEventRecord struct {
	Idx      uint32 // [31:0] sample index of the event
	Kind     uint8  // [39:32] trigger kind
	Ch       uint8  // [43:40] channel
	Rsvd     uint8  // [46:44]
	Overflow bool   // [47:47] events dropped since last read
}

// Unpack decodes one trig_event record from w (LSB-first; needs >= 3 words).
func (r *TrigEventRecord) Unpack(w []uint16) {
	r.Idx = uint32(recGet(w, 0, 32))
	r.Kind = uint8(recGet(w, 32, 8))
	r.Ch = uint8(recGet(w, 40, 4))
	r.Rsvd = uint8(recGet(w, 44, 3))
	r.Overflow = recGet(w, 47, 1) != 0
}

// Pack encodes one trig_event record into 3 words (LSB-first).
func (r TrigEventRecord) Pack() []uint16 {
	w := make([]uint16, 3)
	recSet(w, 0, 32, uint64(r.Idx))
	recSet(w, 32, 8, uint64(r.Kind))
	recSet(w, 40, 4, uint64(r.Ch))
	recSet(w, 44, 3, uint64(r.Rsvd))
	if r.Overflow {
		recSet(w, 47, 1, 1)
	}
	return w
}

// DecodeResultRecord is the decoded decode_result record (64 bits, 4 words). RESERVED (v2): serial-decode result ring — per-transaction spans
type DecodeResultRecord struct {
	Bus      uint8  // [3:0] decode bus id
	Flags    uint8  // [11:4] start/stop/error flags
	Rsvd     uint8  // [14:12]
	Overflow bool   // [15:15] spans dropped since last read
	StartIdx uint32 // [47:16] sample index of transaction start (retroactive anchor)
	Data     uint16 // [63:48] decoded word
}

// Unpack decodes one decode_result record from w (LSB-first; needs >= 4 words).
func (r *DecodeResultRecord) Unpack(w []uint16) {
	r.Bus = uint8(recGet(w, 0, 4))
	r.Flags = uint8(recGet(w, 4, 8))
	r.Rsvd = uint8(recGet(w, 12, 3))
	r.Overflow = recGet(w, 15, 1) != 0
	r.StartIdx = uint32(recGet(w, 16, 32))
	r.Data = uint16(recGet(w, 48, 16))
}

// Pack encodes one decode_result record into 4 words (LSB-first).
func (r DecodeResultRecord) Pack() []uint16 {
	w := make([]uint16, 4)
	recSet(w, 0, 4, uint64(r.Bus))
	recSet(w, 4, 8, uint64(r.Flags))
	recSet(w, 12, 3, uint64(r.Rsvd))
	if r.Overflow {
		recSet(w, 15, 1, 1)
	}
	recSet(w, 16, 32, uint64(r.StartIdx))
	recSet(w, 48, 16, uint64(r.Data))
	return w
}

// burst_drain DMA descriptor codec.
type BurstDrainDescriptor struct {
	SrcSel    uint8  // [7:0] source selector (BURST)
	Plane     uint8  // [11:8] CS plane
	Rsvd      uint8  // [15:12]
	DstPhys   uint32 // [47:16] DMA-coherent destination physical addr
	WordCount uint16 // [63:48] 16-bit words this pass (<=8192)
}

// Pack encodes the burst_drain descriptor into 4 words (LSB-first).
func (d BurstDrainDescriptor) Pack() []uint16 {
	w := make([]uint16, 4)
	recSet(w, 0, 8, uint64(d.SrcSel))
	recSet(w, 8, 4, uint64(d.Plane))
	recSet(w, 12, 4, uint64(d.Rsvd))
	recSet(w, 16, 32, uint64(d.DstPhys))
	recSet(w, 48, 16, uint64(d.WordCount))
	return w
}

// Unpack decodes the burst_drain descriptor from w.
func (d *BurstDrainDescriptor) Unpack(w []uint16) {
	d.SrcSel = uint8(recGet(w, 0, 8))
	d.Plane = uint8(recGet(w, 8, 4))
	d.Rsvd = uint8(recGet(w, 12, 4))
	d.DstPhys = uint32(recGet(w, 16, 32))
	d.WordCount = uint16(recGet(w, 48, 16))
}

// ---- result-channel port triad -------------------------------------------
// ChannelPort names the fixed accessor triad a wired result channel exposes
// (DATA auto-inc read, COUNT level-status, optional RESET strobe).
type ChannelPort struct {
	Name        string
	DataSel     uint16
	CountSel    uint16
	ResetSel    uint16
	HasReset    bool
	RecordWords int
}

// ChannelPorts lists the wired result channels (measure/trig_event/decode arrive
// as their reserved blocks gain registers).
var ChannelPorts = []ChannelPort{
	{"envelope", SelENV_DATA, SelENV_COUNT, SelENV_RESET, true, 3},
}

// ---- behavioral helpers (schema-derived) ---------------------------------

func semOf(plane Plane, sel uint16) Sem {
	for i := range Registers {
		if Registers[i].Plane == plane && Registers[i].Sel == sel {
			return Registers[i].Sem
		}
	}
	return 0
}

// Writable reports whether (plane, sel) is a writable register. It is the bus
// layer's forbidden-write check: false for every read-only register (CONF_DONE,
// all status/drain ports) and for any selector the schema does not define.
func Writable(plane Plane, sel uint16) bool {
	for i := range Registers {
		if Registers[i].Plane == plane && Registers[i].Sel == sel {
			return Registers[i].Access.CanWrite()
		}
	}
	return false
}

// IsAutoInc reports whether reading (plane, sel) pops an auto-increment port —
// the bus layer must never dedup/speculate/CSE such a read.
func IsAutoInc(plane Plane, sel uint16) bool { return semOf(plane, sel)&SemAutoIncPort != 0 }

// IsReadAfterHalt reports whether (plane, sel) is only valid after capture-halt
// (BURST, ENV_DATA, TRIGPOS): the engine reads these only after a HALT.
func IsReadAfterHalt(plane Plane, sel uint16) bool { return semOf(plane, sel)&SemReadAfterHalt != 0 }

// IsLevelStatus reports whether (plane, sel) is a live level (re-read; not sticky).
func IsLevelStatus(plane Plane, sel uint16) bool { return semOf(plane, sel)&SemLevelStatus != 0 }

// Verify checks the fabric identity at bring-up: VERSION == the expected magic
// AND BUILDID_LO/HI == BuildID. A mismatch is a mispaired build (the app generated
// the bitstream), not a negotiation — the caller must refuse to drive the fabric.
func Verify(r func(plane Plane, sel uint16) (uint16, error)) error {
	v, err := r(CS1, SelVERSION)
	if err != nil {
		return fmt.Errorf("iface.Verify: read VERSION: %w", err)
	}
	if v != ExpectVERSION {
		return fmt.Errorf("iface.Verify: VERSION %#04x, want %#04x", v, ExpectVERSION)
	}
	lo, err := r(CS1, SelBUILDID_LO)
	if err != nil {
		return fmt.Errorf("iface.Verify: read BUILDID_LO: %w", err)
	}
	hi, err := r(CS1, SelBUILDID_HI)
	if err != nil {
		return fmt.Errorf("iface.Verify: read BUILDID_HI: %w", err)
	}
	if got := uint32(hi)<<16 | uint32(lo); got != BuildID {
		return fmt.Errorf("iface.Verify: fabric build-ID %#08x, want %#08x (mispaired build)", got, BuildID)
	}
	return nil
}
