// ADC/precision source for the shared acquisition path. No SRAM-ready input:
// every valid word belongs to the source timeline, including during SRAM reads.
// The downstream finite writer or streaming ingress must accept it or fault.
// enable and configuration are core-domain inputs. Configuration is latched at
// enable's rising edge; hold enable low between acquisition epochs. Encode
// clocks remain generated by adc_interleave's fixed 100 MHz phase PLL.
module adc_acquisition_source(
 input wire core,packclk,clk100,enable,
 input wire [79:0] lane,input wire [4:0] decim_log,
 input wire [9:0] encode_enable,
 input wire snapshot_request,output wire snapshot_ack,
 output wire [79:0] snapshot,output wire [4:0] enc_p,enc_n,
 output wire adc_locked,output reg [31:0] data=0,
 output reg valid=0,fault=0,output wire precision_mode
);
 reg enable_q=0,configuration_valid=0,lock_seen=0;
 reg [4:0] decim_l=0;reg [9:0] encode_l=10'h3ff;
 wire legal=decim_log==0 || (decim_log>=4 && decim_log<=20);
 wire run=enable && enable_q && configuration_valid;
 wire [31:0] raw_word,precision_word;
 wire raw_valid,raw_fault,precision_valid,precision_fault;
 assign precision_mode=decim_l!=0;
 adc_interleave frontend(
  .refclk(clk100),.memclk(core),.packclk(packclk),.enable(run),
  .lane(lane),.encode_enable(encode_l),.snapshot_request(snapshot_request),
  .snapshot_ack(snapshot_ack),.consume(run),.word_data(raw_word),
  .valid(raw_valid),.fault(raw_fault),.snapshot(snapshot),
  .enc_p(enc_p),.enc_n(enc_n),.locked(adc_locked));
 adc_precision precision(core,packclk,clk100,run && precision_mode,
  decim_l,raw_word,raw_valid,precision_word,precision_valid,precision_fault);
 always @(posedge core)begin
  enable_q<=enable;
  if(enable && !enable_q)begin
   decim_l<=decim_log;encode_l<=encode_enable;configuration_valid<=legal;
   if(!legal)fault<=1;
  end
  data<=precision_mode ? precision_word : raw_word;
  valid<=run && adc_locked && !fault && !raw_fault && !(precision_mode && precision_fault) &&
         (precision_mode ? precision_valid : raw_valid);
  if(run && adc_locked)lock_seen<=1;
  if(run && lock_seen && !adc_locked)fault<=1;
  if(run && (raw_fault || (precision_mode && precision_fault)))fault<=1;
  if(!enable)begin configuration_valid<=0;valid<=0;fault<=0;lock_seen<=0;end
 end
endmodule
