// lanemap_seed.vh -- the baked ten-core lane map of the default image. GENERATED by
// tools/portspec/lanemapgen.py from docs/acq2/reports/lanecal-2026-09-11/lanecal.json; do not edit (run
// `python3 tools/portspec/lanemapgen.py`, check with `--check`).
//
// SOURCE   lanecal 2026-09-11, image acq_sram revision 3, 100 MHz, ADC IO registers at +4 ns; bit correction scored offline
//          method: Independent CH1/CH2 offset-DAC sweeps, 301 settings x 128 ten-core snapshots; exhaustive 40320 bit permutations x 2 MSB polarities per core.
//          note: Corrects E2 CH2 bit 0 to D16/lane69 and bit 1 to D15/lane68. Other 78 bits retained. Pair membership inherits independent freeze tests from 2026-09-05. DC verifies bit weights, not analog interleave timing.
//
// LAYOUT   80 entries of 7 bits, entry i = 16*k + 8*ch + b = the lane number (default.qsf lane[i],
//          cluster order G2 G3 G4 G5 G6 F16) carrying bit b (0 = LSB .. 7 = MSB) of channel ch
//          (0 = CH1, 1 = CH2) of pair E(k+1), k = 0..4 -- the v2 LANEMAP window (DIAG 0x10 + i)
//          and diag.v's seed order. Core number c = 2*k + ch (0..9).
//          `LANEMAP_SEED_PACKED   560-bit vector, entry i at [7*i+6 : 7*i]; equivalently ten 56-bit
//                                 core fields, core c at [56*c+55 : 56*c], bit b at [7*b+6 : 7*b]
//                                 inside its field (= adc_front's map_ch1 / map_ch2 shape)
//          `LANEMAP_ENTRY(i)      entry i as a 7-bit constant expression (i constant, 0..79)
//          `LANEMAP_CORE(c)       core c as a 56-bit constant expression (c constant, 0..9)
//          `LANEMAP_ENTRY_<i>     entry i as a 7'd literal (the table below)
//          `LANEMAP_SEED_ID       16-bit identity of this map (SHA-256 of the entries, top 16 bits)
//
// USE      constant-array seed:  initial for (i = 0; i < `LANEMAP_N; i = i + 1)
//                                    lanemap[i] = `LANEMAP_ENTRY(i);   -- needs a constant i: use a
//                                generate loop, or `LANEMAP_SEED_PACKED[7*i +: 7] via a localparam:
//                                localparam [`LANEMAP_PACKED_W-1:0] SEED = `LANEMAP_SEED_PACKED;
//          baked assembler:      generate for (c = 0; c < `LANEMAP_CORES; c = c + 1) ...
//                                    wire [55:0] m = `LANEMAP_CORE(c);  bit b <- lane_q[m[7*b +: 7]]

`ifndef LANEMAP_SEED_VH
`define LANEMAP_SEED_VH

`define LANEMAP_N          80
`define LANEMAP_ENTRY_W    7
`define LANEMAP_CORES      10
`define LANEMAP_CORE_W     56
`define LANEMAP_PACKED_W   560
`define LANEMAP_SEED_ID    16'he192

`define LANEMAP_SEED_PACKED 560'h54994a740ad0a25eb16a34ab9228345cb193044a903e70f1b3a48a1300100850418187102848c163868f83023c88d3e24599266ca9d2e1436ec1d3c66ed93170e5b3568f9fbd

`define LANEMAP_ENTRY(i) ((`LANEMAP_SEED_PACKED >> (7 * (i))) & 560'h7f)
`define LANEMAP_CORE(c)  ((`LANEMAP_SEED_PACKED >> (56 * (c))) & 560'hffffffffffffff)

// entry table: `LANEMAP_ENTRY_<i> = lane   // pair ch bit  ball
// core 0 = E1 CH1
`define LANEMAP_ENTRY_0  7'd61   // E1 CH1 bit0  G11
`define LANEMAP_ENTRY_1  7'd63   // E1 CH1 bit1  F10
`define LANEMAP_ENTRY_2  7'd62   // E1 CH1 bit2  E9
`define LANEMAP_ENTRY_3  7'd52   // E1 CH1 bit3  J11
`define LANEMAP_ENTRY_4  7'd53   // E1 CH1 bit4  K11
`define LANEMAP_ENTRY_5  7'd54   // E1 CH1 bit5  K12
`define LANEMAP_ENTRY_6  7'd57   // E1 CH1 bit6  L14
`define LANEMAP_ENTRY_7  7'd56   // E1 CH1 bit7  L13
// core 1 = E1 CH2
`define LANEMAP_ENTRY_8  7'd49   // E1 CH2 bit0  N11
`define LANEMAP_ENTRY_9  7'd50   // E1 CH2 bit1  N12
`define LANEMAP_ENTRY_10 7'd59   // E1 CH2 bit2  N13
`define LANEMAP_ENTRY_11 7'd51   // E1 CH2 bit3  P14
`define LANEMAP_ENTRY_12 7'd60   // E1 CH2 bit4  N14
`define LANEMAP_ENTRY_13 7'd58   // E1 CH2 bit5  M12
`define LANEMAP_ENTRY_14 7'd48   // E1 CH2 bit6  L11
`define LANEMAP_ENTRY_15 7'd55   // E1 CH2 bit7  L12
// core 2 = E2 CH1
`define LANEMAP_ENTRY_16 7'd67   // E2 CH1 bit0  C15
`define LANEMAP_ENTRY_17 7'd66   // E2 CH1 bit1  B16
`define LANEMAP_ENTRY_18 7'd75   // E2 CH1 bit2  A15
`define LANEMAP_ENTRY_19 7'd78   // E2 CH1 bit3  B14
`define LANEMAP_ENTRY_20 7'd74   // E2 CH1 bit4  A14
`define LANEMAP_ENTRY_21 7'd77   // E2 CH1 bit5  B13
`define LANEMAP_ENTRY_22 7'd73   // E2 CH1 bit6  A13
`define LANEMAP_ENTRY_23 7'd76   // E2 CH1 bit7  B12
// core 3 = E2 CH2
`define LANEMAP_ENTRY_24 7'd69   // E2 CH2 bit0  D16
`define LANEMAP_ENTRY_25 7'd68   // E2 CH2 bit1  D15
`define LANEMAP_ENTRY_26 7'd79   // E2 CH2 bit2  F16
`define LANEMAP_ENTRY_27 7'd70   // E2 CH2 bit3  F15
`define LANEMAP_ENTRY_28 7'd72   // E2 CH2 bit4  G16
`define LANEMAP_ENTRY_29 7'd71   // E2 CH2 bit5  G15
`define LANEMAP_ENTRY_30 7'd64   // E2 CH2 bit6  J16
`define LANEMAP_ENTRY_31 7'd65   // E2 CH2 bit7  K16
// core 4 = E3 CH1
`define LANEMAP_ENTRY_32 7'd15   // E3 CH1 bit0  R16
`define LANEMAP_ENTRY_33 7'd13   // E3 CH1 bit1  P15
`define LANEMAP_ENTRY_34 7'd14   // E3 CH1 bit2  P16
`define LANEMAP_ENTRY_35 7'd11   // E3 CH1 bit3  N15
`define LANEMAP_ENTRY_36 7'd12   // E3 CH1 bit4  N16
`define LANEMAP_ENTRY_37 7'd9    // E3 CH1 bit5  L15
`define LANEMAP_ENTRY_38 7'd10   // E3 CH1 bit6  L16
`define LANEMAP_ENTRY_39 7'd8    // E3 CH1 bit7  K15
// core 5 = E3 CH2
`define LANEMAP_ENTRY_40 7'd7    // E3 CH2 bit0  T15
`define LANEMAP_ENTRY_41 7'd3    // E3 CH2 bit1  R14
`define LANEMAP_ENTRY_42 7'd6    // E3 CH2 bit2  T14
`define LANEMAP_ENTRY_43 7'd2    // E3 CH2 bit3  R13
`define LANEMAP_ENTRY_44 7'd5    // E3 CH2 bit4  T13
`define LANEMAP_ENTRY_45 7'd1    // E3 CH2 bit5  R12
`define LANEMAP_ENTRY_46 7'd4    // E3 CH2 bit6  T12
`define LANEMAP_ENTRY_47 7'd0    // E3 CH2 bit7  R11
// core 6 = E4 CH1
`define LANEMAP_ENTRY_48 7'd19   // E4 CH1 bit0  R8
`define LANEMAP_ENTRY_49 7'd20   // E4 CH1 bit1  T8
`define LANEMAP_ENTRY_50 7'd18   // E4 CH1 bit2  P8
`define LANEMAP_ENTRY_51 7'd29   // E4 CH1 bit3  T9
`define LANEMAP_ENTRY_52 7'd27   // E4 CH1 bit4  R9
`define LANEMAP_ENTRY_53 7'd30   // E4 CH1 bit5  T10
`define LANEMAP_ENTRY_54 7'd28   // E4 CH1 bit6  R10
`define LANEMAP_ENTRY_55 7'd31   // E4 CH1 bit7  T11
// core 7 = E4 CH2
`define LANEMAP_ENTRY_56 7'd16   // E4 CH2 bit0  L7
`define LANEMAP_ENTRY_57 7'd21   // E4 CH2 bit1  M9
`define LANEMAP_ENTRY_58 7'd17   // E4 CH2 bit2  N8
`define LANEMAP_ENTRY_59 7'd24   // E4 CH2 bit3  N9
`define LANEMAP_ENTRY_60 7'd25   // E4 CH2 bit4  P9
`define LANEMAP_ENTRY_61 7'd22   // E4 CH2 bit5  M10
`define LANEMAP_ENTRY_62 7'd23   // E4 CH2 bit6  M11
`define LANEMAP_ENTRY_63 7'd26   // E4 CH2 bit7  P11
// core 8 = E5 CH1
`define LANEMAP_ENTRY_64 7'd40   // E5 CH1 bit0  E10
`define LANEMAP_ENTRY_65 7'd36   // E5 CH1 bit1  C11
`define LANEMAP_ENTRY_66 7'd46   // E5 CH1 bit2  E8
`define LANEMAP_ENTRY_67 7'd37   // E5 CH1 bit3  D9
`define LANEMAP_ENTRY_68 7'd35   // E5 CH1 bit4  C9
`define LANEMAP_ENTRY_69 7'd45   // E5 CH1 bit5  D8
`define LANEMAP_ENTRY_70 7'd44   // E5 CH1 bit6  C8
`define LANEMAP_ENTRY_71 7'd47   // E5 CH1 bit7  F8
// core 9 = E5 CH2
`define LANEMAP_ENTRY_72 7'd34   // E5 CH2 bit0  F14
`define LANEMAP_ENTRY_73 7'd33   // E5 CH2 bit1  F13
`define LANEMAP_ENTRY_74 7'd43   // E5 CH2 bit2  F11
`define LANEMAP_ENTRY_75 7'd32   // E5 CH2 bit3  C16
`define LANEMAP_ENTRY_76 7'd39   // E5 CH2 bit4  D12
`define LANEMAP_ENTRY_77 7'd41   // E5 CH2 bit5  E11
`define LANEMAP_ENTRY_78 7'd38   // E5 CH2 bit6  D11
`define LANEMAP_ENTRY_79 7'd42   // E5 CH2 bit7  F9

`endif // LANEMAP_SEED_VH
