#!/usr/bin/env python3
"""Generate the ARM CIC3 compensation/anti-alias filter (requires numpy/scipy)."""
import pathlib,json
import numpy as np
from scipy import signal
root=pathlib.Path(__file__).resolve().parents[2]
x=np.linspace(0,.5,2049)
gain=np.where(x<=.10,1,np.where(x<.2,.5*(1+np.cos(np.pi*(x-.10)/.10)),0))/np.maximum(np.sinc(x)**3,1e-9)
taps=signal.firwin2(63,x,gain,fs=1,window=('kaiser',8));taps/=taps.sum()
q=np.rint(taps*(1<<22)).astype(np.int64);q[31]+=(1<<22)-q.sum()
_,h=signal.freqz(q/(1<<22),worN=2*np.pi*x)
checks=[]
for log in range(4,21):
 cic=(np.sinc(x)/np.sinc(x/(1<<log)))**3
 gain=np.abs(h)*cic
 ripple=float(np.max(np.abs(20*np.log10(gain[x<=.075]))))
 stop=float(20*np.log10(np.max(np.abs(h[x>=.25]))))
 assert ripple<.005 and stop < -90,(log,ripple,stop)
 checks.append(dict(log2=log,passband_fraction=.075,max_passband_error_db=ripple,stopband_from_fraction=.25,stopband_max_db=stop))
s='// Code generated by tools/dsp/precision_filter.py; DO NOT EDIT.\npackage dsp\n\nvar precisionTaps = [...]int32{\n'+','.join(map(str,q))+'}\n'
(root/'app/internal/dsp/precision_taps.go').write_text(s)
(root/'specs/precision-filter-response.json').write_text(json.dumps(checks,indent=2)+'\n')
print('Verified quantized response for every supported decimation: passband error <0.005 dB, stopband < -90 dB')
