#!/usr/bin/env python3
"""Index only original breaker outcomes; never credit disabled USB overlay failures."""
import hashlib
import json
from inventory import ROOT, SOURCE, REV
index = ROOT / 'evidence/test-runs/results.json'
rows = json.loads(index.read_text())
count = 0
for family in ('word','clock','framed'):
    path = ROOT / ('evidence/decode-' + family + '-breakers-source-review.json')
    report = json.loads(path.read_text())
    assert report['exitCode'] == 0 and all(v == 'pass' for v in report['tests'].values())
    for rel, digest in report['runtimeInputSHA256'].items():
        assert hashlib.sha256((SOURCE / rel).read_bytes()).hexdigest() == digest, rel
    log = ROOT / 'evidence' / report['log']
    assert hashlib.sha256(log.read_bytes()).hexdigest() == report['logSHA256']
    count += sum('/' not in n for n in report['tests'])
    run_id = 'decode-' + family + '-breakers'
    rows = [r for r in rows if r['id'] != run_id]
    rows.append(dict(id=run_id, repository='open-sds1000cml-acq2', commit=REV,
                     workingDirectory='app', command=report['command'], environment=report['environment'],
                     exitCode=0, result='pass', log=log.name, sha256=report['logSHA256'],
                     scope='Reviewed original ' + family + ' decoder breaker tests under race detector. Partial assertion coverage only; limitations are in ' + path.name + '. Disabled USB assertions are not passing evidence. No hardware or standards qualification.'))
    report['nextAction'] = 'Review remaining oracle test sources and separate external-runner availability from model completeness.'
    report['nativeIntegration'] = 'Original top-level tests indexed; source-linked test summaries generated by sync_test_evidence.py and go_evidence.py. Disabled USB assertions excluded.'
    path.write_text(json.dumps(report,indent=2)+'\n')
assert count == 12, count
assert not any(r.get('log') == 'decode-usb-enabled-assertions.jsonl' for r in rows)
index.write_text(json.dumps(rows,indent=2)+'\n')
print('PASS: 12 original breaker tests indexed; disabled USB overlay is separate')
