package decode

// oracle_dump_test.go — ORACLE HARNESS for the in-fabric UART decoder.
//
// Runs the app's OWN decode.DecodeUART (the oracle) on a clean synthetic UART
// waveform generated by the same oracleUARTBits/bitsToCodes helpers the repo's
// conformance tests use, and prints a machine-readable line the FPGA-integration
// Verify agent parses to load {THRESH8, SPB(Q16.8)} into the fabric and to
// assert FPGA-drained bytes == DecodeUART().Bytes.
//
// It is a test (package decode) purely so it can reach the test-only generators
// with ZERO reimplementation risk — it asserts nothing, it DUMPS.
//
// Run (defaults = the integer-SPB roundtrip-8n1 oracle vector):
//   cd app && go test ./internal/decode -run TestUARTOracleDump -v
// Parametrised:
//   BAUD=72900 SR=1e6 BITS=8 PARITY=none BYTES=0x13,0x37,0xC0,0xDE \
//     go test ./internal/decode -run TestUARTOracleDump -v
//
// Env:
//   BAUD    baud rate            (default 62500  => SPB 16 @ SR 1e6)
//   SR      sample rate in Hz    (default 1e6)   accepts 1e6 / 1000000
//   BITS    data bits            (default 8)
//   PARITY  none|even|odd        (default none)
//   BYTES   comma hex/dec list   (default 0x48,0x69,0x00,0xFF,0x55,0xAA,0x0F,0xF0,0x21)

import (
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
)

func envDefaultFloat(k string, def float64) float64 {
	if s := os.Getenv(k); s != "" {
		if v, err := strconv.ParseFloat(s, 64); err == nil {
			return v
		}
	}
	return def
}

func envDefaultInt(k string, def int) int {
	if s := os.Getenv(k); s != "" {
		if v, err := strconv.Atoi(s); err == nil {
			return v
		}
	}
	return def
}

func envDefaultStr(k, def string) string {
	if s := os.Getenv(k); s != "" {
		return s
	}
	return def
}

func parseByteList(s string) []int {
	var out []int
	for _, tok := range strings.Split(s, ",") {
		tok = strings.TrimSpace(tok)
		if tok == "" {
			continue
		}
		if v, err := strconv.ParseInt(tok, 0, 0); err == nil {
			out = append(out, int(v)&0xff)
		}
	}
	return out
}

func TestUARTOracleDump(t *testing.T) {
	sr := envDefaultFloat("SR", 1_000_000)
	baud := envDefaultInt("BAUD", 62500)
	bits := envDefaultInt("BITS", 8)
	parity := envDefaultStr("PARITY", "none")
	payload := parseByteList(envDefaultStr("BYTES",
		"0x48,0x69,0x00,0xFF,0x55,0xAA,0x0F,0xF0,0x21"))

	code := oracleUARTBits(sr, float64(baud), bits, parity, frames(payload...))
	codes := bitsToCodes(code)
	r := DecodeUART(codes, 1.0/sr, UARTCfg{Baud: baud, Bits: bits, Parity: parity})
	if !r.OK {
		t.Fatalf("DecodeUART failed: %s", r.Error)
	}

	// Machine-readable oracle summary. THRESH8 = ceil(Thr) is what the host loads
	// into SEL_DEC_THR (0x08); SPB_Q16_8 = round(SPB*256) into SEL_DEC_SPB_LO/HI.
	thresh8 := int(math.Ceil(r.Thr))
	spbQ := int(math.Round(r.SPB * 256.0))

	t.Logf("ORACLE BAUD=%d SR=%g BITS=%d PARITY=%s", baud, sr, bits, parity)
	t.Logf("ORACLE SPB=%.6f THR=%.4f THRESH8=%d SPB_Q16_8=%d(0x%06x)",
		r.SPB, r.Thr, thresh8, spbQ, spbQ)
	t.Logf("ORACLE BYTES=% X", intsToBytes(r.Bytes))
	t.Logf("ORACLE PAYLOAD=% X", intsToBytes(payload))

	// The exact codes (one per column). The FPGA testgen path is validated by the
	// three-way equality testgen==FPGA==DecodeUART(codes); this dumps codes so the
	// same stimulus can drive a bench/sim replay if desired.
	var cb strings.Builder
	for i, c := range codes {
		if i > 0 {
			cb.WriteByte(' ')
		}
		cb.WriteString(strconv.Itoa(int(c)))
	}
	t.Logf("ORACLE NCODES=%d", len(codes))
	t.Logf("ORACLE CODES=%s", cb.String())
}

func intsToBytes(in []int) []byte {
	out := make([]byte, len(in))
	for i, v := range in {
		out[i] = byte(v & 0xff)
	}
	return out
}
